import { UNSPECIFIED, type Skill } from '../types';

export const BULL_CATHEDRAL_SKILLS: readonly Skill[] = [
  // ---- T1 Shield Initiate ----
  {
    id: 'bull.shield_tap',
    name: 'Shield Tap',
    description: 'Basic shield strike that stabilizes footing.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['physical', 'single-target'],
    effects: [
      {
        kind: 'damage',
        description: 'Minor physical damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.guard_up',
    name: 'Guard Up',
    description: 'Raise a defensive stance that grants Guard stacks.',
    ctCost: 20,
    cooldownSec: 6,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Gain Guard stacks and minor mitigation.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
        statTag: 'guard_stacks',
      },
    ],
  },
  {
    id: 'bull.sanctuary_swing',
    name: 'Sanctuary Swing',
    description: 'Heavy swing that scales with current Guard.',
    ctCost: 30,
    cooldownSec: 8,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['burst', 'physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Physical hit with Guard-based bonus scaling.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
        statTag: 'guard_scaling',
      },
    ],
  },
  {
    id: 'bull.oath_line',
    name: 'Oath Line',
    description: 'Marks frontline posture; redirects part of ally damage to self.',
    ctCost: 35,
    cooldownSec: 12,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Allies gain protection; some incoming damage is redirected to caster.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.reprisal_mark',
    name: 'Reprisal Mark',
    description: 'Mark an attacker; marked target takes bonus retaliation damage.',
    ctCost: 25,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'single',
    tags: ['debuff', 'control'],
    effects: [
      {
        kind: 'debuff',
        description: 'Marked target takes increased counter damage.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },

  // ---- T2 Bastion Guard ----
  {
    id: 'bull.bastion_hammer',
    name: 'Bastion Hammer',
    description: 'Basic hammer hit that reinforces sanctuary posture.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['physical', 'single-target'],
    effects: [
      {
        kind: 'damage',
        description: 'Minor physical damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.guard_slam',
    name: 'Guard Slam',
    description: 'Shield slam that consumes some Guard for bonus impact.',
    ctCost: 35,
    cooldownSec: 8,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['burst', 'physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Guard-consuming physical slam.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
        statTag: 'guard_consume',
      },
    ],
  },
  {
    id: 'bull.bulwark_pulse',
    name: 'Bulwark Pulse',
    description: 'Pulse from shield that grants small barriers to allies.',
    ctCost: 30,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'area'],
    effects: [
      {
        kind: 'shield',
        description: 'Grants a small shield to allies.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.sanctum_vow',
    name: 'Sanctum Vow',
    description: 'Defensive oath that boosts mitigation while above Guard threshold.',
    ctCost: 25,
    cooldownSec: 12,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['buff', 'sustain'],
    effects: [
      {
        kind: 'buff',
        description: 'Increased mitigation while Guard remains active.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.wardens_call',
    name: "Warden's Call",
    description: 'Calls enemy focus and generates bonus Guard when struck.',
    ctCost: 20,
    cooldownSec: 14,
    resource: { type: 'none', cost: 0 },
    target: 'global',
    tags: ['control', 'buff'],
    effects: [
      {
        kind: 'status',
        description: 'Taunt-style focus effect and reactive Guard generation.',
        magnitude: UNSPECIFIED,
      },
    ],
  },

  // ---- T3 Fortress Knight ----
  {
    id: 'bull.fortress_strike',
    name: 'Fortress Strike',
    description: 'Basic strike that stabilizes formation.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Minor physical damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.shared_bulwark',
    name: 'Shared Bulwark',
    description: 'Distribute Guard value into party-wide shield support.',
    ctCost: 35,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'buff'],
    effects: [
      {
        kind: 'shield',
        description: 'Allies gain shield scaled by your current Guard.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
        statTag: 'guard_scaling',
      },
    ],
  },
  {
    id: 'bull.pillar_crash',
    name: 'Pillar Crash',
    description: 'Area crash that gains power when shielded.',
    ctCost: 45,
    cooldownSec: 12,
    resource: { type: 'none', cost: 0 },
    target: 'area',
    tags: ['aoe', 'burst', 'physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Area physical damage, increased when Guard is active.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.anchored_stance',
    name: 'Anchored Stance',
    description: 'Root stance that reduces CT costs on defensive skills for a short window.',
    ctCost: 20,
    cooldownSec: 16,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['ct_manipulation', 'buff'],
    effects: [
      {
        kind: 'ct_shift',
        description: 'Short-term CT discount for defensive actions.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.consecrated_wall',
    name: 'Consecrated Wall',
    description: 'Creates a sanctuary wall that dampens incoming damage on allies.',
    ctCost: 40,
    cooldownSec: 18,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'area', 'buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Incoming damage reduced for allies in the sanctuary window.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },

  // ---- T4 Iron Warder ----
  {
    id: 'bull.warder_pike',
    name: 'Warder Pike',
    description: 'Basic thrust that threatens overextended enemies.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Minor physical damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.unyielding_taunt',
    name: 'Unyielding Taunt',
    description: 'Compels target focus; attacking you drains enemy CT.',
    ctCost: 25,
    cooldownSec: 12,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['control', 'ct_manipulation'],
    effects: [
      {
        kind: 'ct_shift',
        description: 'Enemy CT is reduced on attack attempts against you.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.ct_shackle',
    name: 'CT Shackle',
    description: 'Pins target tempo and slows their next actions.',
    ctCost: 35,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'single',
    tags: ['ct_manipulation', 'debuff', 'control'],
    effects: [
      {
        kind: 'debuff',
        description: 'Reduced CT gain for a short duration.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.covenant_ram',
    name: 'Covenant Ram',
    description: 'Forward ram that scales with current mitigation state.',
    ctCost: 45,
    cooldownSec: 14,
    resource: { type: 'none', cost: 0 },
    target: 'cone',
    tags: ['cone', 'burst', 'physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Cone physical impact with mitigation-scaling bonus.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.guard_hegemony',
    name: 'Guard Hegemony',
    description: 'Converts stored Guard into a short dominance window.',
    ctCost: 50,
    cooldownSec: 20,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['ultimate', 'buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Temporary major mitigation and retaliation boost based on Guard spent.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },

  // ---- T5 Immutable Wall ----
  {
    id: 'bull.wallbreaker_maul',
    name: 'Wallbreaker Maul',
    description: 'Basic maul swing that reinforces immutable posture.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['physical'],
    effects: [
      {
        kind: 'damage',
        description: 'Minor physical damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'bull.law_of_shelter',
    name: 'Law of Shelter',
    description: 'Declares a sanctuary period where allied shields cannot be broken below a floor.',
    ctCost: 55,
    cooldownSec: 20,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['ultimate', 'team buff', 'buff'],
    effects: [
      {
        kind: 'shield',
        description: 'Applies shield-floor behavior during the sanctuary window.',
        magnitude: UNSPECIFIED,
      },
    ],
  },
  {
    id: 'bull.citadel_domain',
    name: 'Citadel Domain',
    description: 'Domain aura that boosts ally defense and penalizes enemy damage.',
    ctCost: 45,
    cooldownSec: 16,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'area',
    tags: ['area', 'buff', 'debuff'],
    effects: [
      {
        kind: 'buff',
        description: 'Allies gain defense within the domain.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        kind: 'debuff',
        description: 'Enemies deal reduced damage while inside domain pressure.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.bastion_edict',
    name: 'Bastion Edict',
    description: 'Edict strike that scales from accumulated Guard and marks targets for reprisal.',
    ctCost: 50,
    cooldownSec: 14,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['burst', 'physical', 'debuff'],
    effects: [
      {
        kind: 'damage',
        description: 'High physical strike with Guard-based scaling.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
      {
        kind: 'debuff',
        description: 'Target is marked for increased retaliation damage.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'bull.immovable_decree',
    name: 'Immovable Decree',
    description: 'Capstone decree that anchors ally formation and grants CT resistance.',
    ctCost: 60,
    cooldownSec: 24,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'ct_manipulation', 'buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Allies gain CT-shift resistance and increased stability.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
  },
];
