import { UNSPECIFIED, type Skill } from '../types';

export const DRAKEHORN_SKILLS: readonly Skill[] = [
  // ---- T5 Ember Initiate ----
  {
    id: 'drakehorn.flame_snap',
    name: 'Flame Snap',
    description: 'Basic ranged flame flick.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['ranged', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Small fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.fire_bolt',
    name: 'Fire Bolt',
    description: 'Shoots a bolt of fire.',
    ctCost: 25,
    cooldownSec: 5,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'single',
    tags: ['ranged', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Ranged fire bolt damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.flame_burst',
    name: 'Flame Burst',
    description: 'Explodes on impact, burning the target over time.',
    ctCost: 35,
    cooldownSec: 8,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'single',
    tags: ['dot', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Impact burst damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
      {
        kind: 'dot',
        description: 'DoT: 5% max HP over 4s.',
        magnitude: 0.05,
        magnitudeUnit: 'max_hp_percent',
        durationSec: 4,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.spark_armor',
    name: 'Spark Armor',
    description: 'Burning shield: incoming damage reduced by 10%, attacker takes 10% back.',
    ctCost: 30,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['counter', 'buff'],
    effects: [
      {
        kind: 'shield',
        description: 'Damage taken reduced by 10%.',
        magnitude: 0.1,
        magnitudeUnit: 'percent',
      },
      {
        kind: 'counter',
        description: 'Attacker takes 10% of incoming damage back.',
        magnitude: 0.1,
        magnitudeUnit: 'percent',
      },
    ],
  },
  {
    id: 'drakehorn.combustion',
    name: 'Combustion',
    description: 'Self-buff: next Fire Bolt double hits.',
    ctCost: 40,
    cooldownSec: 12,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['buff'],
    effects: [
      {
        kind: 'buff',
        description: 'Next Fire Bolt hits twice.',
        magnitude: 2,
        magnitudeUnit: 'multiplier',
      },
    ],
  },

  // ---- T4 Flame Berserker ----
  {
    id: 'drakehorn.molten_strike',
    name: 'Molten Strike',
    description: 'Basic flaming punch with small ignite chance.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Basic physical-fire hybrid damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
      {
        kind: 'dot',
        description: 'Small burn chance applied on hit.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
        chance: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.ignite',
    name: 'Ignite',
    description: 'Sacrifice 10% HP to deal large fire damage + ignite DoT.',
    ctCost: 20,
    cooldownSec: 6,
    resource: { type: 'HP', cost: 0.1 },
    target: 'single',
    tags: ['self-damage', 'burst', 'dot', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Large fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
      {
        kind: 'dot',
        description: 'Ignite DoT on target.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.raging_inferno',
    name: 'Raging Inferno',
    description: 'Leap-slam that burns the ground in an AoE.',
    ctCost: 35,
    cooldownSec: 12,
    resource: { type: 'HP', cost: UNSPECIFIED },
    target: 'area',
    tags: ['aoe', 'fire', 'dot'],
    effects: [
      {
        kind: 'damage',
        description: 'AoE fire impact.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
      {
        kind: 'dot',
        description: 'Burning ground DoT.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.berserkers_pact',
    name: "Berserker's Pact",
    description: 'Sacrifice 20% HP to reset all skill cooldowns.',
    ctCost: 0,
    cooldownSec: 15,
    resource: { type: 'HP', cost: 0.2 },
    target: 'self',
    tags: ['ultimate', 'self-sacrifice'],
    effects: [
      {
        kind: 'utility',
        description: 'Reset all skill cooldowns.',
        magnitude: 1,
        magnitudeUnit: 'flat',
      },
    ],
  },
  {
    id: 'drakehorn.rage_fuel',
    name: 'Rage Fuel',
    description: '+25% Attack Speed and +15% damage for 6s.',
    ctCost: 25,
    cooldownSec: 10,
    resource: { type: 'HP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['buff'],
    effects: [
      {
        kind: 'buff',
        description: '+25% Attack Speed.',
        magnitude: 0.25,
        magnitudeUnit: 'percent',
        durationSec: 6,
        statTag: 'attack_speed',
      },
      {
        kind: 'buff',
        description: '+15% damage.',
        magnitude: 0.15,
        magnitudeUnit: 'percent',
        durationSec: 6,
        statTag: 'damage',
      },
    ],
  },

  // ---- T3 Pyre Warlord ----
  {
    id: 'drakehorn.warhammer_smash',
    name: 'Warhammer Smash',
    description: 'Ground strike causing a flame fissure.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'area',
    tags: ['aoe', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Flame fissure damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.warpath',
    name: 'Warpath',
    description: 'Empowers weapon with flame — next 3 attacks explode.',
    ctCost: 50,
    cooldownSec: 8,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'self',
    tags: ['buff', 'multi-hit'],
    effects: [
      {
        kind: 'buff',
        description: 'Next 3 attacks explode (AoE fire).',
        magnitude: 3,
        magnitudeUnit: 'flat',
        statTag: 'charges',
      },
    ],
  },
  {
    id: 'drakehorn.volcanic_eruption',
    name: 'Volcanic Eruption',
    description: 'Huge volcanic blast around self; knockback.',
    ctCost: 60,
    cooldownSec: 18,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'area',
    tags: ['aoe', 'knockback', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Volcanic AoE damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.dragons_breath',
    name: "Dragon's Breath",
    description: 'Cone of flame, burning enemies.',
    ctCost: 45,
    cooldownSec: 12,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'cone',
    tags: ['cone', 'fire', 'dot'],
    effects: [
      {
        kind: 'damage',
        description: 'Cone fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
      {
        kind: 'dot',
        description: 'Burn applied to hit targets.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.battle_cry',
    name: 'Battle Cry',
    description: 'Allies gain +10% Attack and reflect 5% damage for 8s.',
    ctCost: 30,
    cooldownSec: 10,
    resource: { type: 'MP', cost: UNSPECIFIED },
    target: 'allies',
    tags: ['team buff', 'buff'],
    effects: [
      {
        kind: 'buff',
        description: '+10% Attack.',
        magnitude: 0.1,
        magnitudeUnit: 'percent',
        durationSec: 8,
        statTag: 'attack',
      },
      {
        kind: 'counter',
        description: 'Reflect 5% incoming damage.',
        magnitude: 0.05,
        magnitudeUnit: 'percent',
        durationSec: 8,
      },
    ],
  },

  // ---- T2 Inferno Executioner ----
  {
    id: 'drakehorn.blazing_axe',
    name: 'Blazing Axe',
    description: 'Heavy swing that burns deeply.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Heavy physical-fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.hellfire',
    name: 'Hellfire',
    description: 'Engulfs target in flames for massive DoT.',
    ctCost: 70,
    cooldownSec: 20,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['dot', 'single-target', 'fire'],
    effects: [
      {
        kind: 'dot',
        description: 'Massive single-target DoT.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.demolisher',
    name: 'Demolisher',
    description: 'Flaming grenades at an area.',
    ctCost: 50,
    cooldownSec: 15,
    resource: { type: 'none', cost: 0 },
    target: 'area',
    tags: ['aoe', 'physical', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'AoE grenade damage.',
        magnitude: UNSPECIFIED,
        damageType: 'physical',
      },
    ],
  },
  {
    id: 'drakehorn.executioners_flame',
    name: "Executioner's Flame",
    description: 'Instantly kills one low-HP enemy (≤10% HP); otherwise deals large damage.',
    ctCost: 60,
    cooldownSec: 18,
    resource: { type: 'none', cost: 0 },
    target: 'single',
    tags: ['execute', 'fire'],
    effects: [
      {
        kind: 'execute',
        description: 'Instant kill below 10% HP.',
        magnitude: 0.1,
        magnitudeUnit: 'max_hp_percent',
      },
      {
        kind: 'damage',
        description: 'Fallback high fire damage if execute fails.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.final_blaze',
    name: 'Final Blaze',
    description: 'Self-immolation: sacrifices 20% HP for massive AoE damage.',
    ctCost: 90,
    cooldownSec: 30,
    resource: { type: 'HP', cost: 0.2 },
    target: 'global',
    tags: ['self-sacrifice', 'aoe', 'ultimate', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Enormous AoE fire damage to all enemies.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },

  // ---- T1 Apocalypse Bringer ----
  {
    id: 'drakehorn.world_on_fire',
    name: 'World on Fire',
    description: 'Every basic attack ignites the ground for splash damage.',
    ctCost: UNSPECIFIED,
    cooldownSec: 0,
    resource: { type: 'none', cost: 0 },
    target: 'area',
    tags: ['aoe', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Splash fire damage on basic attack.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.cataclysm',
    name: 'Cataclysm',
    description: 'Catastrophic flame meteor across a huge AoE.',
    ctCost: 100,
    cooldownSec: 25,
    resource: { type: 'none', cost: 0 },
    target: 'global',
    tags: ['ultimate', 'aoe', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Meteor AoE fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.black_hole',
    name: 'Black Hole',
    description: 'Fiery vortex pulls enemies, dealing continuous damage.',
    ctCost: 70,
    cooldownSec: 18,
    resource: { type: 'none', cost: 0 },
    target: 'area',
    tags: ['aoe', 'pull', 'dot', 'fire'],
    effects: [
      {
        kind: 'damage',
        description: 'Pull + continuous fire damage.',
        magnitude: UNSPECIFIED,
        damageType: 'fire',
      },
    ],
  },
  {
    id: 'drakehorn.wrath_of_the_phoenix',
    name: 'Wrath of the Phoenix',
    description: 'On lethal damage, resurrect with 50% HP once per fight.',
    ctCost: 80,
    cooldownSec: 20,
    resource: { type: 'none', cost: 0 },
    target: 'self',
    tags: ['passive-buff'],
    effects: [
      {
        kind: 'heal',
        description: 'Self-revive with 50% HP.',
        magnitude: 0.5,
        magnitudeUnit: 'max_hp_percent',
      },
    ],
  },
  {
    id: 'drakehorn.end_of_days',
    name: 'End of Days',
    description: 'Instantly kills all enemies below 25% HP.',
    ctCost: 120,
    cooldownSec: 60,
    resource: { type: 'none', cost: 0 },
    target: 'global',
    tags: ['execute', 'aoe'],
    effects: [
      {
        kind: 'execute',
        description: 'Execute all enemies below 25% HP.',
        magnitude: 0.25,
        magnitudeUnit: 'max_hp_percent',
      },
    ],
  },
];
