import type { BrandIconSlug, SolidIconSlug } from './types';

// Literal require() calls — Metro resolves paths at bundle time from the string literal.
// Slug keys use underscores; file names in the source pack sometimes use hyphens and spaces.
// Do not replace these with template literals or computed paths — Metro will not bundle them.

export const SOLID_ICONS: Readonly<Record<SolidIconSlug, number>> = {
  ad: require('../../../assets/icons/PNG/for-light-mode/48px/solid/ad.png'),
  align_center: require('../../../assets/icons/PNG/for-light-mode/48px/solid/align-center.png'),
  align_justify: require('../../../assets/icons/PNG/for-light-mode/48px/solid/align-justify.png'),
  align_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/align-left.png'),
  align_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/align-right.png'),
  analytics: require('../../../assets/icons/PNG/for-light-mode/48px/solid/analytics.png'),
  angle_down: require('../../../assets/icons/PNG/for-light-mode/48px/solid/angle-down.png'),
  angle_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/angle-left.png'),
  angle_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/angle-right.png'),
  angle_up: require('../../../assets/icons/PNG/for-light-mode/48px/solid/angle-up.png'),
  arrow_alt_circle_down: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-alt circle down.png'),
  arrow_alt_circle_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-alt circle left.png'),
  arrow_alt_circle_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-alt circle right.png'),
  arrow_alt_circle_up: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-alt circle up.png'),
  arrow_circle_down: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-circle down.png'),
  arrow_circle_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-circle left.png'),
  arrow_circle_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-circle right.png'),
  arrow_circle_up: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-circle up.png'),
  arrow_down: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-down.png'),
  arrow_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-left.png'),
  arrow_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-right.png'),
  arrow_up: require('../../../assets/icons/PNG/for-light-mode/48px/solid/arrow-up.png'),
  at: require('../../../assets/icons/PNG/for-light-mode/48px/solid/at.png'),
  badge_check: require('../../../assets/icons/PNG/for-light-mode/48px/solid/badge-check.png'),
  bank: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bank.png'),
  bars: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bars.png'),
  bell_exclaimation: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bell-exclaimation.png'),
  bell_mute: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bell-mute.png'),
  bell: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bell.png'),
  bold: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bold.png'),
  bolt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bolt.png'),
  book_heart: require('../../../assets/icons/PNG/for-light-mode/48px/solid/book-heart.png'),
  bookmark: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bookmark.png'),
  box_usd: require('../../../assets/icons/PNG/for-light-mode/48px/solid/box-usd.png'),
  brightness_high: require('../../../assets/icons/PNG/for-light-mode/48px/solid/brightness-high.png'),
  brightness_low: require('../../../assets/icons/PNG/for-light-mode/48px/solid/brightness-low.png'),
  bullet_list: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bullet-list.png'),
  bullhorn: require('../../../assets/icons/PNG/for-light-mode/48px/solid/bullhorn.png'),
  calender: require('../../../assets/icons/PNG/for-light-mode/48px/solid/calender.png'),
  cc: require('../../../assets/icons/PNG/for-light-mode/48px/solid/cc.png'),
  chart_line: require('../../../assets/icons/PNG/for-light-mode/48px/solid/chart-line.png'),
  chart_network: require('../../../assets/icons/PNG/for-light-mode/48px/solid/chart-network.png'),
  check_box: require('../../../assets/icons/PNG/for-light-mode/48px/solid/check-box.png'),
  check_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/check-circle.png'),
  check_list: require('../../../assets/icons/PNG/for-light-mode/48px/solid/check-list.png'),
  check: require('../../../assets/icons/PNG/for-light-mode/48px/solid/check.png'),
  chevron_down: require('../../../assets/icons/PNG/for-light-mode/48px/solid/chevron-down.png'),
  chevron_up: require('../../../assets/icons/PNG/for-light-mode/48px/solid/chevron-up.png'),
  circle_notch: require('../../../assets/icons/PNG/for-light-mode/48px/solid/circle-notch.png'),
  clipboard: require('../../../assets/icons/PNG/for-light-mode/48px/solid/clipboard.png'),
  clock: require('../../../assets/icons/PNG/for-light-mode/48px/solid/clock.png'),
  cloud_download: require('../../../assets/icons/PNG/for-light-mode/48px/solid/cloud-download.png'),
  cloud_upload: require('../../../assets/icons/PNG/for-light-mode/48px/solid/cloud-upload.png'),
  code_block: require('../../../assets/icons/PNG/for-light-mode/48px/solid/code-block.png'),
  code: require('../../../assets/icons/PNG/for-light-mode/48px/solid/code.png'),
  cog: require('../../../assets/icons/PNG/for-light-mode/48px/solid/cog.png'),
  comment_dots: require('../../../assets/icons/PNG/for-light-mode/48px/solid/comment-dots.png'),
  comment_quote: require('../../../assets/icons/PNG/for-light-mode/48px/solid/comment-quote.png'),
  comment: require('../../../assets/icons/PNG/for-light-mode/48px/solid/comment.png'),
  comments: require('../../../assets/icons/PNG/for-light-mode/48px/solid/comments.png'),
  copy: require('../../../assets/icons/PNG/for-light-mode/48px/solid/copy.png'),
  credit_card: require('../../../assets/icons/PNG/for-light-mode/48px/solid/credit-card.png'),
  crown: require('../../../assets/icons/PNG/for-light-mode/48px/solid/crown.png'),
  divider: require('../../../assets/icons/PNG/for-light-mode/48px/solid/divider.png'),
  download_alt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/download-alt.png'),
  download: require('../../../assets/icons/PNG/for-light-mode/48px/solid/download.png'),
  edit: require('../../../assets/icons/PNG/for-light-mode/48px/solid/edit.png'),
  ellipses_horizontal_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/ellipses-horizontal circle.png'),
  ellipses_horizontal: require('../../../assets/icons/PNG/for-light-mode/48px/solid/ellipses-horizontal.png'),
  ellipses_vertical_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/ellipses-vertical circle.png'),
  ellipses_vertical: require('../../../assets/icons/PNG/for-light-mode/48px/solid/ellipses-vertical.png'),
  envelope: require('../../../assets/icons/PNG/for-light-mode/48px/solid/envelope.png'),
  exclaimation: require('../../../assets/icons/PNG/for-light-mode/48px/solid/exclaimation.png'),
  exclamation_triangle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/exclamation-triangle.png'),
  expand: require('../../../assets/icons/PNG/for-light-mode/48px/solid/expand.png'),
  external_link: require('../../../assets/icons/PNG/for-light-mode/48px/solid/external-link.png'),
  eye_cross: require('../../../assets/icons/PNG/for-light-mode/48px/solid/eye-cross.png'),
  eye: require('../../../assets/icons/PNG/for-light-mode/48px/solid/eye.png'),
  face_thinking: require('../../../assets/icons/PNG/for-light-mode/48px/solid/face-thinking.png'),
  file_import: require('../../../assets/icons/PNG/for-light-mode/48px/solid/file-import.png'),
  filter_alt_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/filter-alt circle.png'),
  filter: require('../../../assets/icons/PNG/for-light-mode/48px/solid/filter.png'),
  fire: require('../../../assets/icons/PNG/for-light-mode/48px/solid/fire.png'),
  flag_checkered: require('../../../assets/icons/PNG/for-light-mode/48px/solid/flag-checkered.png'),
  flag: require('../../../assets/icons/PNG/for-light-mode/48px/solid/flag.png'),
  folder_open: require('../../../assets/icons/PNG/for-light-mode/48px/solid/folder-open.png'),
  folder: require('../../../assets/icons/PNG/for-light-mode/48px/solid/folder.png'),
  globe_americas: require('../../../assets/icons/PNG/for-light-mode/48px/solid/globe-americas.png'),
  globe: require('../../../assets/icons/PNG/for-light-mode/48px/solid/globe.png'),
  grid: require('../../../assets/icons/PNG/for-light-mode/48px/solid/grid.png'),
  heading_1: require('../../../assets/icons/PNG/for-light-mode/48px/solid/heading-1.png'),
  heading_2: require('../../../assets/icons/PNG/for-light-mode/48px/solid/heading-2.png'),
  heading_3: require('../../../assets/icons/PNG/for-light-mode/48px/solid/heading-3.png'),
  headphones: require('../../../assets/icons/PNG/for-light-mode/48px/solid/headphones.png'),
  heart: require('../../../assets/icons/PNG/for-light-mode/48px/solid/heart.png'),
  highlight: require('../../../assets/icons/PNG/for-light-mode/48px/solid/highlight.png'),
  hockey_mask: require('../../../assets/icons/PNG/for-light-mode/48px/solid/hockey-mask.png'),
  home: require('../../../assets/icons/PNG/for-light-mode/48px/solid/home.png'),
  image: require('../../../assets/icons/PNG/for-light-mode/48px/solid/image.png'),
  indent: require('../../../assets/icons/PNG/for-light-mode/48px/solid/indent.png'),
  info_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/info-circle.png'),
  italics: require('../../../assets/icons/PNG/for-light-mode/48px/solid/italics.png'),
  lightbulb: require('../../../assets/icons/PNG/for-light-mode/48px/solid/lightbulb.png'),
  line_height: require('../../../assets/icons/PNG/for-light-mode/48px/solid/line-height.png'),
  link: require('../../../assets/icons/PNG/for-light-mode/48px/solid/link.png'),
  location_pin: require('../../../assets/icons/PNG/for-light-mode/48px/solid/location-pin.png'),
  lock_alt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/lock-alt.png'),
  lock_open: require('../../../assets/icons/PNG/for-light-mode/48px/solid/lock-open.png'),
  lock: require('../../../assets/icons/PNG/for-light-mode/48px/solid/lock.png'),
  login: require('../../../assets/icons/PNG/for-light-mode/48px/solid/login.png'),
  logout: require('../../../assets/icons/PNG/for-light-mode/48px/solid/logout.png'),
  message_dots: require('../../../assets/icons/PNG/for-light-mode/48px/solid/message-dots.png'),
  message: require('../../../assets/icons/PNG/for-light-mode/48px/solid/message.png'),
  minus: require('../../../assets/icons/PNG/for-light-mode/48px/solid/minus.png'),
  moon: require('../../../assets/icons/PNG/for-light-mode/48px/solid/moon.png'),
  music: require('../../../assets/icons/PNG/for-light-mode/48px/solid/music.png'),
  newspaper: require('../../../assets/icons/PNG/for-light-mode/48px/solid/newspaper.png'),
  numbered_list: require('../../../assets/icons/PNG/for-light-mode/48px/solid/numbered-list.png'),
  octagon_check: require('../../../assets/icons/PNG/for-light-mode/48px/solid/octagon-check.png'),
  octagon_times: require('../../../assets/icons/PNG/for-light-mode/48px/solid/octagon-times.png'),
  outdent: require('../../../assets/icons/PNG/for-light-mode/48px/solid/outdent.png'),
  page_break: require('../../../assets/icons/PNG/for-light-mode/48px/solid/page-break.png'),
  paperclip: require('../../../assets/icons/PNG/for-light-mode/48px/solid/paperclip.png'),
  paragraph: require('../../../assets/icons/PNG/for-light-mode/48px/solid/paragraph.png'),
  pause: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pause.png'),
  pen_nib: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pen-nib.png'),
  pen: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pen.png'),
  pencil_ruler: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pencil-ruler.png'),
  pencil: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pencil.png'),
  people_carry: require('../../../assets/icons/PNG/for-light-mode/48px/solid/people-carry.png'),
  phone_ringing_high: require('../../../assets/icons/PNG/for-light-mode/48px/solid/phone-ringing high.png'),
  phone_ringing_low: require('../../../assets/icons/PNG/for-light-mode/48px/solid/phone-ringing low.png'),
  plane_departure: require('../../../assets/icons/PNG/for-light-mode/48px/solid/plane-departure.png'),
  plane: require('../../../assets/icons/PNG/for-light-mode/48px/solid/plane.png'),
  play: require('../../../assets/icons/PNG/for-light-mode/48px/solid/play.png'),
  playlist: require('../../../assets/icons/PNG/for-light-mode/48px/solid/playlist.png'),
  plus: require('../../../assets/icons/PNG/for-light-mode/48px/solid/plus.png'),
  print: require('../../../assets/icons/PNG/for-light-mode/48px/solid/print.png'),
  pro: require('../../../assets/icons/PNG/for-light-mode/48px/solid/pro.png'),
  question: require('../../../assets/icons/PNG/for-light-mode/48px/solid/question.png'),
  quote_left: require('../../../assets/icons/PNG/for-light-mode/48px/solid/quote-left.png'),
  quote_right: require('../../../assets/icons/PNG/for-light-mode/48px/solid/quote-right.png'),
  receipt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/receipt.png'),
  refresh: require('../../../assets/icons/PNG/for-light-mode/48px/solid/refresh.png'),
  retro_camera: require('../../../assets/icons/PNG/for-light-mode/48px/solid/retro-camera.png'),
  robot: require('../../../assets/icons/PNG/for-light-mode/48px/solid/robot.png'),
  save: require('../../../assets/icons/PNG/for-light-mode/48px/solid/save.png'),
  search: require('../../../assets/icons/PNG/for-light-mode/48px/solid/search.png'),
  seedlings: require('../../../assets/icons/PNG/for-light-mode/48px/solid/seedlings.png'),
  share: require('../../../assets/icons/PNG/for-light-mode/48px/solid/share.png'),
  shop: require('../../../assets/icons/PNG/for-light-mode/48px/solid/shop.png'),
  shopping_cart: require('../../../assets/icons/PNG/for-light-mode/48px/solid/shopping-cart.png'),
  shuffle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/shuffle.png'),
  sort: require('../../../assets/icons/PNG/for-light-mode/48px/solid/sort.png'),
  sound_mute: require('../../../assets/icons/PNG/for-light-mode/48px/solid/sound-mute.png'),
  sound_on: require('../../../assets/icons/PNG/for-light-mode/48px/solid/sound-on.png'),
  sparkles: require('../../../assets/icons/PNG/for-light-mode/48px/solid/sparkles.png'),
  spinner_third: require('../../../assets/icons/PNG/for-light-mode/48px/solid/spinner-third.png'),
  spinner: require('../../../assets/icons/PNG/for-light-mode/48px/solid/spinner.png'),
  star_crescent: require('../../../assets/icons/PNG/for-light-mode/48px/solid/star-crescent.png'),
  star: require('../../../assets/icons/PNG/for-light-mode/48px/solid/star.png'),
  strike_through: require('../../../assets/icons/PNG/for-light-mode/48px/solid/strike-through.png'),
  sun: require('../../../assets/icons/PNG/for-light-mode/48px/solid/sun.png'),
  table: require('../../../assets/icons/PNG/for-light-mode/48px/solid/table.png'),
  tag: require('../../../assets/icons/PNG/for-light-mode/48px/solid/tag.png'),
  text_slash: require('../../../assets/icons/PNG/for-light-mode/48px/solid/text-slash.png'),
  themes: require('../../../assets/icons/PNG/for-light-mode/48px/solid/themes.png'),
  thumbsdown: require('../../../assets/icons/PNG/for-light-mode/48px/solid/thumbsdown.png'),
  thumbsup: require('../../../assets/icons/PNG/for-light-mode/48px/solid/thumbsup.png'),
  thumbtack: require('../../../assets/icons/PNG/for-light-mode/48px/solid/thumbtack.png'),
  times_circle: require('../../../assets/icons/PNG/for-light-mode/48px/solid/times-circle.png'),
  times: require('../../../assets/icons/PNG/for-light-mode/48px/solid/times.png'),
  translate: require('../../../assets/icons/PNG/for-light-mode/48px/solid/translate.png'),
  trash_alt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/trash-alt.png'),
  trash: require('../../../assets/icons/PNG/for-light-mode/48px/solid/trash.png'),
  trending: require('../../../assets/icons/PNG/for-light-mode/48px/solid/trending.png'),
  trophy: require('../../../assets/icons/PNG/for-light-mode/48px/solid/trophy.png'),
  underline: require('../../../assets/icons/PNG/for-light-mode/48px/solid/underline.png'),
  unlock_alt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/unlock-alt.png'),
  unlock: require('../../../assets/icons/PNG/for-light-mode/48px/solid/unlock.png'),
  upload_alt: require('../../../assets/icons/PNG/for-light-mode/48px/solid/upload-alt.png'),
  upload: require('../../../assets/icons/PNG/for-light-mode/48px/solid/upload.png'),
  user_check: require('../../../assets/icons/PNG/for-light-mode/48px/solid/user-check.png'),
  user_headset: require('../../../assets/icons/PNG/for-light-mode/48px/solid/user-headset.png'),
  user: require('../../../assets/icons/PNG/for-light-mode/48px/solid/user.png'),
  users_crown: require('../../../assets/icons/PNG/for-light-mode/48px/solid/users-crown.png'),
  users: require('../../../assets/icons/PNG/for-light-mode/48px/solid/users.png'),
  vote_yeah: require('../../../assets/icons/PNG/for-light-mode/48px/solid/vote-yeah.png'),
  wallet: require('../../../assets/icons/PNG/for-light-mode/48px/solid/wallet.png'),
  window_close: require('../../../assets/icons/PNG/for-light-mode/48px/solid/window-close.png'),
};

export const BRAND_ICONS: Readonly<Record<BrandIconSlug, number>> = {
  android: require('../../../assets/icons/PNG/for-light-mode/48px/brands/android.png'),
  angellist: require('../../../assets/icons/PNG/for-light-mode/48px/brands/angellist.png'),
  apple: require('../../../assets/icons/PNG/for-light-mode/48px/brands/apple.png'),
  arweave: require('../../../assets/icons/PNG/for-light-mode/48px/brands/arweave.png'),
  behance: require('../../../assets/icons/PNG/for-light-mode/48px/brands/behance.png'),
  bloomberg: require('../../../assets/icons/PNG/for-light-mode/48px/brands/bloomberg.png'),
  bluesky: require('../../../assets/icons/PNG/for-light-mode/48px/brands/bluesky.png'),
  crunchbase: require('../../../assets/icons/PNG/for-light-mode/48px/brands/crunchbase.png'),
  digg: require('../../../assets/icons/PNG/for-light-mode/48px/brands/digg.png'),
  discord: require('../../../assets/icons/PNG/for-light-mode/48px/brands/discord.png'),
  discourse: require('../../../assets/icons/PNG/for-light-mode/48px/brands/discourse.png'),
  facebook_round: require('../../../assets/icons/PNG/for-light-mode/48px/brands/facebook-round.png'),
  figma: require('../../../assets/icons/PNG/for-light-mode/48px/brands/figma.png'),
  giphy: require('../../../assets/icons/PNG/for-light-mode/48px/brands/giphy.png'),
  github: require('../../../assets/icons/PNG/for-light-mode/48px/brands/github.png'),
  golden: require('../../../assets/icons/PNG/for-light-mode/48px/brands/golden.png'),
  google_news: require('../../../assets/icons/PNG/for-light-mode/48px/brands/google-news.png'),
  google: require('../../../assets/icons/PNG/for-light-mode/48px/brands/google.png'),
  hackernoon: require('../../../assets/icons/PNG/for-light-mode/48px/brands/hackernoon.png'),
  huggingface: require('../../../assets/icons/PNG/for-light-mode/48px/brands/huggingface.png'),
  imgur: require('../../../assets/icons/PNG/for-light-mode/48px/brands/imgur.png'),
  instagram: require('../../../assets/icons/PNG/for-light-mode/48px/brands/instagram.png'),
  kaggle: require('../../../assets/icons/PNG/for-light-mode/48px/brands/kaggle.png'),
  linkedin: require('../../../assets/icons/PNG/for-light-mode/48px/brands/linkedin.png'),
  mastodon: require('../../../assets/icons/PNG/for-light-mode/48px/brands/mastodon.png'),
  minds: require('../../../assets/icons/PNG/for-light-mode/48px/brands/minds.png'),
  newsbreak: require('../../../assets/icons/PNG/for-light-mode/48px/brands/newsbreak.png'),
  npm: require('../../../assets/icons/PNG/for-light-mode/48px/brands/npm.png'),
  open_ai: require('../../../assets/icons/PNG/for-light-mode/48px/brands/open-ai.png'),
  pinterest: require('../../../assets/icons/PNG/for-light-mode/48px/brands/pinterest.png'),
  podcasts: require('../../../assets/icons/PNG/for-light-mode/48px/brands/podcasts.png'),
  product_hunt: require('../../../assets/icons/PNG/for-light-mode/48px/brands/product-hunt.png'),
  reddit: require('../../../assets/icons/PNG/for-light-mode/48px/brands/reddit.png'),
  rss: require('../../../assets/icons/PNG/for-light-mode/48px/brands/rss.png'),
  sia: require('../../../assets/icons/PNG/for-light-mode/48px/brands/sia.png'),
  steam: require('../../../assets/icons/PNG/for-light-mode/48px/brands/steam.png'),
  threads: require('../../../assets/icons/PNG/for-light-mode/48px/brands/threads.png'),
  tiktok: require('../../../assets/icons/PNG/for-light-mode/48px/brands/tiktok.png'),
  twitch: require('../../../assets/icons/PNG/for-light-mode/48px/brands/twitch.png'),
  twitter: require('../../../assets/icons/PNG/for-light-mode/48px/brands/twitter.png'),
  unsplash: require('../../../assets/icons/PNG/for-light-mode/48px/brands/unsplash.png'),
  viewblocks: require('../../../assets/icons/PNG/for-light-mode/48px/brands/viewblocks.png'),
  wikipedia: require('../../../assets/icons/PNG/for-light-mode/48px/brands/wikipedia.png'),
  x: require('../../../assets/icons/PNG/for-light-mode/48px/brands/x.png'),
  youtube: require('../../../assets/icons/PNG/for-light-mode/48px/brands/youtube.png'),
};

export function resolveSolidIcon(slug: SolidIconSlug): number | undefined {
  return SOLID_ICONS[slug];
}

export function resolveBrandIcon(slug: BrandIconSlug): number | undefined {
  return BRAND_ICONS[slug];
}

export function hasSolidIcon(slug: string): slug is SolidIconSlug {
  return Object.prototype.hasOwnProperty.call(SOLID_ICONS, slug);
}

export function hasBrandIcon(slug: string): slug is BrandIconSlug {
  return Object.prototype.hasOwnProperty.call(BRAND_ICONS, slug);
}
