/**
 * AUTO-GENERATED by scripts/generateSpriteRegistry.js
 * Generated: 2026-03-28T13:47:16.817Z
 * Do not edit manually — re-run the script when sprite assets change.
 */

import type { CharacterId, CharacterManifest } from './types';

export const SPRITE_REGISTRY: Record<CharacterId, CharacterManifest> = {
  AceWild: {
    characterId: 'AceWild',
    displayName: 'Ace',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-atk.png'),
        meta: { frameDelays: [4,4,4,5,5,4,4,3,3,4,3,4,4,3,3,4,3,4,4,3,4,4,4,4,5,5,4,4,4,4,5,5,5,5,4,3], frameWidth: 372, frameHeight: 98, frameCount: 36, imageWidth: 13392 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-dead.png'),
        meta: { frameDelays: [10], frameWidth: 73, frameHeight: 34, frameCount: 1, imageWidth: 73 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-dying.png'),
        meta: { frameDelays: [10], frameWidth: 54, frameHeight: 44, frameCount: 1, imageWidth: 54 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 94, frameHeight: 76, frameCount: 4, imageWidth: 376 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-limit_atk.png'),
        meta: { frameDelays: [4,2,3,3,5,5,8,6,6,6,4,5,5,4,4,8,10,6,6,8,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,8,6,4,4,4,4,3,3,3,3], frameWidth: 608, frameHeight: 463, frameCount: 49, imageWidth: 29792 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 140, frameHeight: 79, frameCount: 4, imageWidth: 560 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 108, frameHeight: 82, frameCount: 4, imageWidth: 432 },
      },
      move: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-move.png'),
        meta: { frameDelays: [10], frameWidth: 59, frameHeight: 65, frameCount: 1, imageWidth: 59 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 94, frameHeight: 81, frameCount: 4, imageWidth: 376 },
      },
      win: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-win.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 131, frameHeight: 123, frameCount: 4, imageWidth: 524 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/AceWild/254001507-win_before.png'),
        meta: { frameDelays: [6,3,3,4,4,6,4,5,4,4,6,6,8,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4], frameWidth: 156, frameHeight: 159, frameCount: 58, imageWidth: 9048 },
      },
    },
  },
  EdwardFMA: {
    characterId: 'EdwardFMA',
    displayName: 'Edward',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-atk.png'),
        meta: { frameDelays: [4,8,6,6,10,6,12,8,6,6,6,4,4,4,4,4,4,6,8,3,3,6,6,12,6,6,4,4,6,6,4,6,6,6,6,6,6,6,6,6], frameWidth: 191, frameHeight: 158, frameCount: 40, imageWidth: 7640 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-dead.png'),
        meta: { frameDelays: [4], frameWidth: 71, frameHeight: 33, frameCount: 1, imageWidth: 71 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-dying.png'),
        meta: { frameDelays: [4], frameWidth: 59, frameHeight: 36, frameCount: 1, imageWidth: 59 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 79, frameHeight: 72, frameCount: 4, imageWidth: 316 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-limit_atk.png'),
        meta: { frameDelays: [6,8,4,4,4,4,6,8,6,4,6,6,4,4,6,6,6,6,6,6,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,2,2,4,4,6,6,4,4,4,6,6,6,4,4,4,6,8,8,8,6,6,8,8,8,24,6], frameWidth: 520, frameHeight: 158, frameCount: 61, imageWidth: 31720 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 107, frameHeight: 71, frameCount: 4, imageWidth: 428 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-magic_standby.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 101, frameHeight: 71, frameCount: 4, imageWidth: 404 },
      },
      move: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-move.png'),
        meta: { frameDelays: [4], frameWidth: 53, frameHeight: 68, frameCount: 1, imageWidth: 53 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-standby.png'),
        meta: { frameDelays: [12,12,12,11], frameWidth: 79, frameHeight: 69, frameCount: 4, imageWidth: 316 },
      },
      win: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-win.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 56, frameHeight: 72, frameCount: 4, imageWidth: 224 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/EdwardFMA/338000107-win_before.png'),
        meta: { frameDelays: [8,8,6,6,8,4,6,8,8,8,8,8,8,8,8], frameWidth: 82, frameHeight: 72, frameCount: 15, imageWidth: 1230 },
      },
    },
  },
  KingMont: {
    characterId: 'KingMont',
    displayName: 'King Mont',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-atk.png'),
        meta: { frameDelays: [6,10,6,4,5,6,6,4,5,6,6,6,6,6], frameWidth: 186, frameHeight: 208, frameCount: 14, imageWidth: 2604 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-dead.png'),
        meta: { frameDelays: [4], frameWidth: 116, frameHeight: 53, frameCount: 1, imageWidth: 116 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-dying.png'),
        meta: { frameDelays: [4], frameWidth: 91, frameHeight: 76, frameCount: 1, imageWidth: 91 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 120, frameHeight: 78, frameCount: 4, imageWidth: 480 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-limit_atk.png'),
        meta: { frameDelays: [9,8,8,8,7,6,6,7,6,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,7,8,8,8,7,7], frameWidth: 379, frameHeight: 340, frameCount: 43, imageWidth: 16297 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 117, frameHeight: 123, frameCount: 4, imageWidth: 468 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-magic_standby.png'),
        meta: { frameDelays: [5,5,5,5], frameWidth: 99, frameHeight: 91, frameCount: 4, imageWidth: 396 },
      },
      move: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-move.png'),
        meta: { frameDelays: [5], frameWidth: 101, frameHeight: 69, frameCount: 1, imageWidth: 101 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 125, frameHeight: 73, frameCount: 4, imageWidth: 500 },
      },
      win: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-win.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 104, frameHeight: 122, frameCount: 4, imageWidth: 416 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/KingMont/339000607-win_before.png'),
        meta: { frameDelays: [7,6,5,5,5,5,5,7,7,8,8,8,8,8,8,8], frameWidth: 126, frameHeight: 122, frameCount: 16, imageWidth: 2016 },
      },
    },
  },
  Lenneth: {
    characterId: 'Lenneth',
    displayName: 'Lenneth',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-atk.png'),
        meta: { frameDelays: [4,6,6,4,3,4,3,3,3,4,6,3,6,3,3,8,3,4], frameWidth: 193, frameHeight: 108, frameCount: 18, imageWidth: 3474 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-dead.png'),
        meta: { frameDelays: [4], frameWidth: 71, frameHeight: 36, frameCount: 1, imageWidth: 71 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-dying.png'),
        meta: { frameDelays: [4], frameWidth: 74, frameHeight: 50, frameCount: 1, imageWidth: 74 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-idle.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 97, frameHeight: 73, frameCount: 8, imageWidth: 776 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-limit_atk.png'),
        meta: { frameDelays: [5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,3,4,6,6,4,4,4,4,5,6,4,4,4,6,4,4,5,5,8,6,6,5,5,8,6,6,4,4,8,6,6,5,5,5,5,6,8,8,4,4,6,8,8,6,10,8,8,6,6,8,8,6,6,5,5,6,6,4,4,4,6,6,8,8,12,10,8,6,5,4,4,4,4,4,6,6,8,10,10,10,8,8,8,4,6,8,8,8,8,4,6,6], frameWidth: 474, frameHeight: 497, frameCount: 108, imageWidth: 51192 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4,4,4,4,4], frameWidth: 105, frameHeight: 88, frameCount: 8, imageWidth: 840 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 109, frameHeight: 73, frameCount: 8, imageWidth: 872 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-move.png'),
        meta: { frameDelays: [4], frameWidth: 88, frameHeight: 66, frameCount: 1, imageWidth: 88 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-standby.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 110, frameHeight: 73, frameCount: 8, imageWidth: 880 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-win.png'),
        meta: { frameDelays: [10,10,10,10,10,10,10,10], frameWidth: 97, frameHeight: 73, frameCount: 8, imageWidth: 776 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Lenneth/330000107-win_before.png'),
        meta: { frameDelays: [3,3,3,8,8,3,4,4,6,6,6,6,6,10,10,10,10,10,10,10,10], frameWidth: 146, frameHeight: 107, frameCount: 21, imageWidth: 3066 },
      },
    },
  },
  LightningOdin: {
    characterId: 'LightningOdin',
    displayName: 'Lightning (Odin)',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-atk.png'),
        meta: { frameDelays: [5,5,0,3,3,3,5,5,5,5,5,5,5,5,5,5,5,5,10,12,14,14], frameWidth: 335, frameHeight: 294, frameCount: 22, imageWidth: 7370 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-dead.png'),
        meta: { frameDelays: [6], frameWidth: 65, frameHeight: 35, frameCount: 1, imageWidth: 65 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-dying.png'),
        meta: { frameDelays: [6], frameWidth: 54, frameHeight: 43, frameCount: 1, imageWidth: 54 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-idle.png'),
        meta: { frameDelays: [16,16,16,16], frameWidth: 110, frameHeight: 116, frameCount: 4, imageWidth: 440 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-limit_atk.png'),
        meta: { frameDelays: [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,4,5,2,3,4,4,4,4,4,4,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,6,7,8,10,12], frameWidth: 480, frameHeight: 518, frameCount: 72, imageWidth: 34560 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 141, frameHeight: 130, frameCount: 4, imageWidth: 564 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-magic_standby.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 136, frameHeight: 116, frameCount: 4, imageWidth: 544 },
      },
      move: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-move.png'),
        meta: { frameDelays: [5], frameWidth: 123, frameHeight: 103, frameCount: 1, imageWidth: 123 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 114, frameHeight: 120, frameCount: 4, imageWidth: 456 },
      },
      win: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-win.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 178, frameHeight: 126, frameCount: 4, imageWidth: 712 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/LightningOdin/213001007-win_before.png'),
        meta: { frameDelays: [8,8,8,5,5,5,5,5,5,5,5,5,5,5,5,6,7,5,5,5,5,5,5,10,10,10,10,10,10,10,10], frameWidth: 212, frameHeight: 258, frameCount: 31, imageWidth: 6572 },
      },
    },
  },
  LightningX1: {
    characterId: 'LightningX1',
    displayName: 'Lightning',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-atk.png'),
        meta: { frameDelays: [6,3,3,5,4,3,3,3,3,3,4,6,4,4,4,4,4,4,4,5,5,5,6,6,5,5,5,8,6,6,6,6,5,10], frameWidth: 237, frameHeight: 195, frameCount: 34, imageWidth: 8058, anchor: { fromRight: 62, fromBottom: 70 } },
      },
      dead: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-dead.png'),
        meta: { frameDelays: [6], frameWidth: 81, frameHeight: 57, frameCount: 1, imageWidth: 81, anchor: { fromRight: 34, fromBottom: 21 } },
      },
      dying: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-dying.png'),
        meta: { frameDelays: [6], frameWidth: 58, frameHeight: 59, frameCount: 1, imageWidth: 58, anchor: { fromRight: 32, fromBottom: 17 } },
      },
      idle: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 73, frameHeight: 78, frameCount: 4, imageWidth: 292, anchor: { fromRight: 42, fromBottom: 25 } },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-limit_atk.png'),
        meta: { frameDelays: [6,7,8,8,4,4,4,4,6,4,4,6,4,4,5,6,7,8,6,6,6,7,7,5,6,8,8,10,5,5,5,5,6,8,8,4,6,8,6,5,5,8,6,7,8,10,5,6,5,5,6,5,5,6,7,8,8,7,10], frameWidth: 297, frameHeight: 227, frameCount: 59, imageWidth: 17523, anchor: { fromRight: 94, fromBottom: 86 } },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 89, frameHeight: 83, frameCount: 4, imageWidth: 356, anchor: { fromRight: 42, fromBottom: 25 } },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 73, frameHeight: 83, frameCount: 4, imageWidth: 292, anchor: { fromRight: 42, fromBottom: 25 } },
      },
      move: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-move.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 77, frameHeight: 74, frameCount: 4, imageWidth: 308, anchor: { fromRight: 46, fromBottom: 25 } },
      },
      standby: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 87, frameHeight: 77, frameCount: 4, imageWidth: 348, anchor: { fromRight: 42, fromBottom: 25 } },
      },
      win: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-win.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 73, frameHeight: 78, frameCount: 4, imageWidth: 292, anchor: { fromRight: 42, fromBottom: 25 } },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/LightningX1/213000107-win_before.png'),
        meta: { frameDelays: [4,4,6,4,6,6,6,6,6,8,5,8,12,12,12,12], frameWidth: 87, frameHeight: 92, frameCount: 16, imageWidth: 1392, anchor: { fromRight: 42, fromBottom: 25 } },
      },
    },
  },
  LightningX2: {
    characterId: 'LightningX2',
    displayName: 'Lightning II',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-atk.png'),
        meta: { frameDelays: [3,3,5,5,5,5,5,5,6,6,2,3,4,4,3,4,5,4,2,3,3,3,3,3,4,4,4,5,5,5,4,4,4,3,2,3,4,5,6,6,4,4,3,3,5,4], frameWidth: 258, frameHeight: 176, frameCount: 46, imageWidth: 11868, anchor: { fromRight: 53, fromBottom: 40 } },
      },
      dead: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-dead.png'),
        meta: { frameDelays: [5], frameWidth: 68, frameHeight: 59, frameCount: 1, imageWidth: 68, anchor: { fromRight: 27, fromBottom: 20 } },
      },
      dying: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-dying.png'),
        meta: { frameDelays: [5], frameWidth: 69, frameHeight: 50, frameCount: 1, imageWidth: 69, anchor: { fromRight: 28, fromBottom: 11 } },
      },
      idle: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-idle.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 91, frameHeight: 77, frameCount: 8, imageWidth: 728, anchor: { fromRight: 37, fromBottom: 11 } },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-limit_atk.png'),
        meta: { frameDelays: [3,3,4,4,3,3,4,4,5,5,3,3,4,4,5,5,6,4,5,6,4,4,4,4,4,4,4,4,4,5,4,4,4,4,4,5,4,6,7,6,5,4,3,4,4,4,4,4,4,4,4,4,4,5,6,6,6,6,6,6,6,6,6,6,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6,4,4,4,4,4,4,4,4], frameWidth: 328, frameHeight: 458, frameCount: 88, imageWidth: 28864, anchor: { fromRight: 67, fromBottom: 78 } },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-magic_atk.png'),
        meta: { frameDelays: [3,3,3,3,3,3,3,3], frameWidth: 102, frameHeight: 76, frameCount: 8, imageWidth: 816, anchor: { fromRight: 37, fromBottom: 18 } },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-magic_standby.png'),
        meta: { frameDelays: [4,4,4,4,4,4,4,4], frameWidth: 88, frameHeight: 78, frameCount: 8, imageWidth: 704, anchor: { fromRight: 38, fromBottom: 11 } },
      },
      move: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-move.png'),
        meta: { frameDelays: [5], frameWidth: 90, frameHeight: 64, frameCount: 1, imageWidth: 90, anchor: { fromRight: 25, fromBottom: 11 } },
      },
      standby: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-standby.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 109, frameHeight: 77, frameCount: 8, imageWidth: 872, anchor: { fromRight: 37, fromBottom: 11 } },
      },
      win: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-win.png'),
        meta: { frameDelays: [16,16,16,16], frameWidth: 74, frameHeight: 69, frameCount: 4, imageWidth: 296, anchor: { fromRight: 22, fromBottom: 11 } },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/LightningX2/250000207-win_before.png'),
        meta: { frameDelays: [8,6,5,4,3,4,5,5,6,7,6,4,4,5,6,7,8,9,10,11,12], frameWidth: 118, frameHeight: 109, frameCount: 21, imageWidth: 2478, anchor: { fromRight: 48, fromBottom: 20 } },
      },
    },
  },
  LightningX3: {
    characterId: 'LightningX3',
    displayName: 'Lightning III',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-atk.png'),
        meta: { frameDelays: [6,4,4,5,6,8,4,4,5,8,3,4,4,5,6,8,4,4,5,6,8,10,8,6], frameWidth: 235, frameHeight: 111, frameCount: 24, imageWidth: 5640 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-dead.png'),
        meta: { frameDelays: [4], frameWidth: 72, frameHeight: 58, frameCount: 1, imageWidth: 72 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-dying.png'),
        meta: { frameDelays: [4], frameWidth: 79, frameHeight: 53, frameCount: 1, imageWidth: 79 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-idle.png'),
        meta: { frameDelays: [4,3,4,3,14,14,3,3,4,4,5,6,3,14,14,14], frameWidth: 112, frameHeight: 116, frameCount: 16, imageWidth: 1792 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-limit_atk.png'),
        meta: { frameDelays: [4,4,4,4,3,4,6,8,9,10,6,4,6,5,6,7,8,9,4,4,6,7,8,4,6,8,4,3,4,5,6,8,7,6,5,4,6,6,6,4,6], frameWidth: 528, frameHeight: 585, frameCount: 41, imageWidth: 21648 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4,4,4,4,4], frameWidth: 108, frameHeight: 78, frameCount: 8, imageWidth: 864 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 98, frameHeight: 87, frameCount: 8, imageWidth: 784 },
      },
      move: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-move.png'),
        meta: { frameDelays: [4], frameWidth: 107, frameHeight: 91, frameCount: 1, imageWidth: 107 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-standby.png'),
        meta: { frameDelays: [16,16,16,4,4,4,4,16,16,4,4,4,4,16], frameWidth: 112, frameHeight: 116, frameCount: 14, imageWidth: 1568 },
      },
      win: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-win.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 80, frameHeight: 70, frameCount: 4, imageWidth: 320 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/LightningX3/258000207-win_before.png'),
        meta: { frameDelays: [8,9,10,2,3,4,8,6,8,6,12,6,7,8,9], frameWidth: 108, frameHeight: 106, frameCount: 15, imageWidth: 1620 },
      },
    },
  },
  Nier2B: {
    characterId: 'Nier2B',
    displayName: '2B',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-atk.png'),
        meta: { frameDelays: [5,5,6,7,5,5,5,6,5,5,5,6,6,5,4,4,5,5,6,8,10,4,6,8,8,5,4,4,4,4,4,4,4,4,4,4,5,5,6,8,12,12,12,12], frameWidth: 323, frameHeight: 254, frameCount: 44, imageWidth: 14212 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-dead.png'),
        meta: { frameDelays: [5], frameWidth: 84, frameHeight: 41, frameCount: 1, imageWidth: 84 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-dying.png'),
        meta: { frameDelays: [5], frameWidth: 75, frameHeight: 73, frameCount: 1, imageWidth: 75 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 77, frameHeight: 92, frameCount: 4, imageWidth: 308 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,7,8,8,8,6,9,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,8,10,10,10,10], frameWidth: 591, frameHeight: 383, frameCount: 50, imageWidth: 29550 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 95, frameHeight: 88, frameCount: 4, imageWidth: 380 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 84, frameHeight: 87, frameCount: 4, imageWidth: 336 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-move.png'),
        meta: { frameDelays: [5], frameWidth: 84, frameHeight: 70, frameCount: 1, imageWidth: 84 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 79, frameHeight: 92, frameCount: 4, imageWidth: 316 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-win.png'),
        meta: { frameDelays: [10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10], frameWidth: 72, frameHeight: 82, frameCount: 24, imageWidth: 1728 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Nier2B/310000107-win_before.png'),
        meta: { frameDelays: [12,6,4,6,8,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10], frameWidth: 85, frameHeight: 89, frameCount: 20, imageWidth: 1700 },
      },
    },
  },
  Nier9S: {
    characterId: 'Nier9S',
    displayName: '9S',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-atk.png'),
        meta: { frameDelays: [8,4,6,6,4,6,8,4,4,4,4,4,4,4,4,6,8,6,6,8,6,8,8,6,6,6,6,6], frameWidth: 508, frameHeight: 158, frameCount: 28, imageWidth: 14224 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-dead.png'),
        meta: { frameDelays: [5], frameWidth: 78, frameHeight: 48, frameCount: 1, imageWidth: 78 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-dying.png'),
        meta: { frameDelays: [5], frameWidth: 75, frameHeight: 62, frameCount: 1, imageWidth: 75 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 75, frameHeight: 92, frameCount: 4, imageWidth: 300 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-limit_atk.png'),
        meta: { frameDelays: [6,4,4,4,6,8,6,6,4,6,8,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,4,4,6,6,6], frameWidth: 156, frameHeight: 116, frameCount: 71, imageWidth: 11076 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 91, frameHeight: 92, frameCount: 4, imageWidth: 364 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 76, frameHeight: 92, frameCount: 4, imageWidth: 304 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-move.png'),
        meta: { frameDelays: [3], frameWidth: 77, frameHeight: 66, frameCount: 1, imageWidth: 77 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 78, frameHeight: 92, frameCount: 4, imageWidth: 312 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-win.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 79, frameHeight: 92, frameCount: 4, imageWidth: 316 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Nier9S/310000206-win_before.png'),
        meta: { frameDelays: [5,8,6,10,10,10,10,6,6,10,8,8,8,6,8,8,8,8,8,8,8], frameWidth: 86, frameHeight: 95, frameCount: 21, imageWidth: 1806 },
      },
    },
  },
  NierA2: {
    characterId: 'NierA2',
    displayName: 'A2',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-atk.png'),
        meta: { frameDelays: [8,7,8,9,8,8,4,5,6,5,5,5,6,9,7,7,20], frameWidth: 264, frameHeight: 252, frameCount: 17, imageWidth: 4488 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-dead.png'),
        meta: { frameDelays: [5], frameWidth: 68, frameHeight: 62, frameCount: 1, imageWidth: 68 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-dying.png'),
        meta: { frameDelays: [5], frameWidth: 64, frameHeight: 59, frameCount: 1, imageWidth: 64 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 72, frameHeight: 92, frameCount: 4, imageWidth: 288 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-limit_atk.png'),
        meta: { frameDelays: [60,9,9,9,9,9,9,9,9,8,6,6,6,6,6,6,6,6,6,5,5,5,5,2,4,3,6,6,7,7,7,8,8,8,8,8,8,8,8,8,8,5,5,5,5,9], frameWidth: 238, frameHeight: 179, frameCount: 46, imageWidth: 10948 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 78, frameHeight: 83, frameCount: 4, imageWidth: 312 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 72, frameHeight: 88, frameCount: 4, imageWidth: 288 },
      },
      move: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-move.png'),
        meta: { frameDelays: [5], frameWidth: 64, frameHeight: 52, frameCount: 1, imageWidth: 64 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 89, frameHeight: 92, frameCount: 4, imageWidth: 356 },
      },
      win: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-win.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8,8,8,8,8], frameWidth: 52, frameHeight: 70, frameCount: 12, imageWidth: 624 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/NierA2/401001207-win_before.png'),
        meta: { frameDelays: [8,9,5,7,7,6,8,7,5,5,6,6,6,8], frameWidth: 110, frameHeight: 106, frameCount: 14, imageWidth: 1540 },
      },
    },
  },
  Olberic: {
    characterId: 'Olberic',
    displayName: 'Olberic',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-atk.png'),
        meta: { frameDelays: [6,8,3,3,8,8,5,3,5,5,5], frameWidth: 225, frameHeight: 88, frameCount: 11, imageWidth: 2475 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-dead.png'),
        meta: { frameDelays: [6], frameWidth: 70, frameHeight: 47, frameCount: 1, imageWidth: 70 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-dying.png'),
        meta: { frameDelays: [6], frameWidth: 54, frameHeight: 58, frameCount: 1, imageWidth: 54 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-idle.png'),
        meta: { frameDelays: [7,7,7,7,7,7,7,7], frameWidth: 85, frameHeight: 83, frameCount: 8, imageWidth: 680 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,6,6,6,8,6,6,8,4,4,6,15,6,4,3,3,3,2,6,8,6,3,3,3,3,3,3,3,3,3,6,6], frameWidth: 229, frameHeight: 253, frameCount: 39, imageWidth: 8931 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-magic_atk.png'),
        meta: { frameDelays: [5,5,5,5], frameWidth: 114, frameHeight: 80, frameCount: 4, imageWidth: 456 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-magic_standby.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 85, frameHeight: 80, frameCount: 4, imageWidth: 340 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-move.png'),
        meta: { frameDelays: [4], frameWidth: 70, frameHeight: 71, frameCount: 1, imageWidth: 70 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-standby.png'),
        meta: { frameDelays: [5,5,5,5,5,5,5,5], frameWidth: 85, frameHeight: 80, frameCount: 8, imageWidth: 680 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-win.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 63, frameHeight: 77, frameCount: 4, imageWidth: 252 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Olberic/334000207-win_before.png'),
        meta: { frameDelays: [8,6,6,8,18,10,10,8,8,8,8,8], frameWidth: 82, frameHeight: 81, frameCount: 12, imageWidth: 984 },
      },
    },
  },
  Primrose: {
    characterId: 'Primrose',
    displayName: 'Primrose',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-atk.png'),
        meta: { frameDelays: [5,5,5,5,5,5,5,5,5,6,7,7,7,7,7,7,7,7,7,8,10,7,7,7,7], frameWidth: 167, frameHeight: 203, frameCount: 25, imageWidth: 4175 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-dead.png'),
        meta: { frameDelays: [6], frameWidth: 74, frameHeight: 33, frameCount: 1, imageWidth: 74 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-dying.png'),
        meta: { frameDelays: [6], frameWidth: 53, frameHeight: 52, frameCount: 1, imageWidth: 53 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-idle.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6], frameWidth: 75, frameHeight: 87, frameCount: 8, imageWidth: 600 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,5,5,5,5,5,5], frameWidth: 270, frameHeight: 157, frameCount: 55, imageWidth: 14850 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-magic_atk.png'),
        meta: { frameDelays: [5,5,5,5], frameWidth: 81, frameHeight: 87, frameCount: 4, imageWidth: 324 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-magic_standby.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 82, frameHeight: 87, frameCount: 4, imageWidth: 328 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-move.png'),
        meta: { frameDelays: [4], frameWidth: 59, frameHeight: 75, frameCount: 1, imageWidth: 59 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-standby.png'),
        meta: { frameDelays: [8,4,8,4,8,4,8,4], frameWidth: 75, frameHeight: 87, frameCount: 8, imageWidth: 600 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-win.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 53, frameHeight: 74, frameCount: 4, imageWidth: 212 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Primrose/334000107-win_before.png'),
        meta: { frameDelays: [5,5,5,5,5,5,6,6,6,8,8,10,6,10,7,7,7,7,7,8,8,8,8], frameWidth: 74, frameHeight: 87, frameCount: 23, imageWidth: 1702 },
      },
    },
  },
  RainDemon: {
    characterId: 'RainDemon',
    displayName: 'Rain (Demon)',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-atk.png'),
        meta: { frameDelays: [3,3,3,3,3,3,3,10,5,5,5,5,5,5,10], frameWidth: 211, frameHeight: 116, frameCount: 15, imageWidth: 3165 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-dead.png'),
        meta: { frameDelays: [50], frameWidth: 101, frameHeight: 60, frameCount: 1, imageWidth: 101 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-dying.png'),
        meta: { frameDelays: [3], frameWidth: 69, frameHeight: 66, frameCount: 1, imageWidth: 69 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-idle.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 105, frameHeight: 101, frameCount: 8, imageWidth: 840 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-limit_atk.png'),
        meta: { frameDelays: [3,3,3,3,3,5,6,6,6,6,6,6,3,6,5,5,5,3,3,3,3,3,5,3,3,10], frameWidth: 239, frameHeight: 164, frameCount: 26, imageWidth: 6214 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 96, frameHeight: 95, frameCount: 4, imageWidth: 384 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 82, frameHeight: 97, frameCount: 4, imageWidth: 328 },
      },
      move: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-move.png'),
        meta: { frameDelays: [3,3,3,3], frameWidth: 87, frameHeight: 95, frameCount: 4, imageWidth: 348 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-standby.png'),
        meta: { frameDelays: [13,13,13,13], frameWidth: 82, frameHeight: 97, frameCount: 4, imageWidth: 328 },
      },
      win: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-win.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 92, frameHeight: 101, frameCount: 8, imageWidth: 736 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/RainDemon/401000205-win_before.png'),
        meta: { frameDelays: [6,6,6,6,6,8,10,10,13,13,13,13], frameWidth: 99, frameHeight: 101, frameCount: 12, imageWidth: 1188 },
      },
    },
  },
  RainKing: {
    characterId: 'RainKing',
    displayName: 'Rain (King)',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-atk.png'),
        meta: { frameDelays: [6,6,8,12,4,2,2,2,8,8,8,8,6,2,3,8,8,8,12,24,10,2,4,6,6,3,4,4], frameWidth: 200, frameHeight: 167, frameCount: 28, imageWidth: 5600 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-dead.png'),
        meta: { frameDelays: [5], frameWidth: 87, frameHeight: 64, frameCount: 1, imageWidth: 87 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-dying.png'),
        meta: { frameDelays: [5], frameWidth: 69, frameHeight: 66, frameCount: 1, imageWidth: 69 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-idle.png'),
        meta: { frameDelays: [14,14,14,14], frameWidth: 101, frameHeight: 89, frameCount: 4, imageWidth: 404 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-limit_atk.png'),
        meta: { frameDelays: [6,8,2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,6,6,5,5,6,6,6,8,8,8,8], frameWidth: 367, frameHeight: 304, frameCount: 51, imageWidth: 18717 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 128, frameHeight: 89, frameCount: 4, imageWidth: 512 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-magic_standby.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 100, frameHeight: 89, frameCount: 4, imageWidth: 400 },
      },
      move: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-move.png'),
        meta: { frameDelays: [3], frameWidth: 100, frameHeight: 67, frameCount: 1, imageWidth: 100 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 115, frameHeight: 89, frameCount: 4, imageWidth: 460 },
      },
      win: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-win.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 95, frameHeight: 94, frameCount: 4, imageWidth: 380 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/RainKing/100023207-win_before.png'),
        meta: { frameDelays: [8,6,8,6,8,8,4,4,4,4,8,8,8,8,8,12,12,12,12,12,12,12], frameWidth: 150, frameHeight: 153, frameCount: 22, imageWidth: 3300 },
      },
    },
  },
  RainNormal: {
    characterId: 'RainNormal',
    displayName: 'Rain (Normal)',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-atk.png'),
        meta: { frameDelays: [3,3,3,3,3,3,3,10,3,3,4,5,5,5,10], frameWidth: 224, frameHeight: 118, frameCount: 15, imageWidth: 3360 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-dead.png'),
        meta: { frameDelays: [50], frameWidth: 88, frameHeight: 52, frameCount: 1, imageWidth: 88 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-dying.png'),
        meta: { frameDelays: [3], frameWidth: 63, frameHeight: 65, frameCount: 1, imageWidth: 63 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-idle.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 106, frameHeight: 90, frameCount: 8, imageWidth: 848 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-limit_atk.png'),
        meta: { frameDelays: [3,3,2,4,5,6,6,6,6,5,3,3,3,3,3,3,3,3,3,3,3,3,10], frameWidth: 375, frameHeight: 206, frameCount: 23, imageWidth: 8625 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 92, frameHeight: 69, frameCount: 4, imageWidth: 368 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 78, frameHeight: 60, frameCount: 4, imageWidth: 312 },
      },
      move: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-move.png'),
        meta: { frameDelays: [3,3,3,3], frameWidth: 81, frameHeight: 63, frameCount: 4, imageWidth: 324 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-standby.png'),
        meta: { frameDelays: [9,8,9,10], frameWidth: 91, frameHeight: 96, frameCount: 4, imageWidth: 364 },
      },
      win: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-win.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 92, frameHeight: 98, frameCount: 8, imageWidth: 736 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/RainNormal/100000106-win_before.png'),
        meta: { frameDelays: [6,6,6,6,6,8,10,10,13,13,13,13], frameWidth: 99, frameHeight: 98, frameCount: 12, imageWidth: 1188 },
      },
    },
  },
  RoyNV: {
    characterId: 'RoyNV',
    displayName: 'Roy Mustang',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-atk.png'),
        meta: { frameDelays: [5,2,3,6,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3], frameWidth: 300, frameHeight: 104, frameCount: 26, imageWidth: 7800 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-dead.png'),
        meta: { frameDelays: [10], frameWidth: 88, frameHeight: 39, frameCount: 1, imageWidth: 88 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-dying.png'),
        meta: { frameDelays: [5], frameWidth: 53, frameHeight: 50, frameCount: 1, imageWidth: 53 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 72, frameHeight: 77, frameCount: 4, imageWidth: 288 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,3,4,5,6,6,3,4,5,6,6,6,6,3,4,5,6,6,3,4,5,6,6,6,6,3,4,5,6,8,9,3,4,5,6,6,6,6,6,6,6,6,6,6,6,6,6], frameWidth: 386, frameHeight: 444, frameCount: 54, imageWidth: 20844 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6], frameWidth: 99, frameHeight: 73, frameCount: 4, imageWidth: 396 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8], frameWidth: 75, frameHeight: 84, frameCount: 4, imageWidth: 300 },
      },
      move: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-move.png'),
        meta: { frameDelays: [5], frameWidth: 88, frameHeight: 70, frameCount: 1, imageWidth: 88 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-standby.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 72, frameHeight: 77, frameCount: 4, imageWidth: 288 },
      },
      win: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-win.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 72, frameHeight: 78, frameCount: 4, imageWidth: 288 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/RoyNV/338000307-win_before.png'),
        meta: { frameDelays: [7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,9,10,10,10,10,10,10,10,10], frameWidth: 86, frameHeight: 86, frameCount: 27, imageWidth: 2322 },
      },
    },
  },
  Serah: {
    characterId: 'Serah',
    displayName: 'Serah',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Serah/250000107-atk.png'),
        meta: { frameDelays: [4,4,4,4,6,4,4,4,4,3,3,3,4,4,4,4,2,2,2,5,4,3,3,3,3,6,5,5,3,4,4,4,4,4,4,4,8,5,5,8,4,4,4], frameWidth: 219, frameHeight: 118, frameCount: 43, imageWidth: 9417 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Serah/250000107-dead.png'),
        meta: { frameDelays: [4], frameWidth: 66, frameHeight: 34, frameCount: 1, imageWidth: 66 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Serah/250000107-dying.png'),
        meta: { frameDelays: [4], frameWidth: 53, frameHeight: 45, frameCount: 1, imageWidth: 53 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Serah/250000107-idle.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 78, frameHeight: 68, frameCount: 8, imageWidth: 624 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Serah/250000107-limit_atk.png'),
        meta: { frameDelays: [4,4,4,4,6,4,4,4,6,6,4,5,5,5,5,7,7,8,4,4,4,5,5,5,7,6,6,6,6,6,6,6,4,4,6,6,6,8,12,4,6,6,6,6,6,6,6,6,6], frameWidth: 434, frameHeight: 526, frameCount: 49, imageWidth: 21266 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Serah/250000107-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4,4,4,4,4], frameWidth: 95, frameHeight: 76, frameCount: 8, imageWidth: 760 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Serah/250000107-magic_standby.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 84, frameHeight: 83, frameCount: 8, imageWidth: 672 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Serah/250000107-move.png'),
        meta: { frameDelays: [4], frameWidth: 76, frameHeight: 64, frameCount: 1, imageWidth: 76 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Serah/250000107-standby.png'),
        meta: { frameDelays: [12,12,12,12,12,12,12,12], frameWidth: 80, frameHeight: 68, frameCount: 8, imageWidth: 640 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Serah/250000107-win.png'),
        meta: { frameDelays: [11,11,11,11], frameWidth: 62, frameHeight: 76, frameCount: 4, imageWidth: 248 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Serah/250000107-win_before.png'),
        meta: { frameDelays: [3,3,4,4,5,5,5,6,6,6,6,6,4,8,10,6], frameWidth: 79, frameHeight: 133, frameCount: 16, imageWidth: 1264 },
      },
    },
  },
  Therion: {
    characterId: 'Therion',
    displayName: 'Therion',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Therion/334000306-atk.png'),
        meta: { frameDelays: [6,6,8,6,6,8,6,6,4,4], frameWidth: 256, frameHeight: 179, frameCount: 10, imageWidth: 2560 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Therion/334000306-dead.png'),
        meta: { frameDelays: [6], frameWidth: 72, frameHeight: 37, frameCount: 1, imageWidth: 72 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Therion/334000306-dying.png'),
        meta: { frameDelays: [6], frameWidth: 54, frameHeight: 52, frameCount: 1, imageWidth: 54 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Therion/334000306-idle.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6], frameWidth: 74, frameHeight: 88, frameCount: 8, imageWidth: 592 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Therion/334000306-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,5,5,5,5,8,8,8,8,6,6,6,6,6,6,6,6,6], frameWidth: 302, frameHeight: 225, frameCount: 22, imageWidth: 6644 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Therion/334000306-magic_atk.png'),
        meta: { frameDelays: [5,5,5,5], frameWidth: 95, frameHeight: 65, frameCount: 4, imageWidth: 380 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Therion/334000306-magic_standby.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 73, frameHeight: 70, frameCount: 4, imageWidth: 292 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Therion/334000306-move.png'),
        meta: { frameDelays: [4], frameWidth: 69, frameHeight: 66, frameCount: 1, imageWidth: 69 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Therion/334000306-standby.png'),
        meta: { frameDelays: [10,5,10,5,10,5,10,5], frameWidth: 73, frameHeight: 75, frameCount: 8, imageWidth: 584 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Therion/334000306-win.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 90, frameHeight: 70, frameCount: 4, imageWidth: 360 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Therion/334000306-win_before.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,10,4,10,6,6,6,3,10,6,10,10,10,10,10,6,10,8,8,8,8], frameWidth: 93, frameHeight: 94, frameCount: 27, imageWidth: 2511 },
      },
    },
  },
  Tilith: {
    characterId: 'Tilith',
    displayName: 'Tilith',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,7,8,9,4,4,4,4,4,6,6,6,6,6,6,6,6], frameWidth: 165, frameHeight: 165, frameCount: 24, imageWidth: 3960 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-dead.png'),
        meta: { frameDelays: [5], frameWidth: 64, frameHeight: 49, frameCount: 1, imageWidth: 64 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-dying.png'),
        meta: { frameDelays: [5], frameWidth: 60, frameHeight: 52, frameCount: 1, imageWidth: 60 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-idle.png'),
        meta: { frameDelays: [14,14,14,14,14,14,14,14,14,14,14,14], frameWidth: 73, frameHeight: 83, frameCount: 12, imageWidth: 876 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-limit_atk.png'),
        meta: { frameDelays: [7,7,7,7,6,6,6,6,6,7,8,9,10,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6], frameWidth: 162, frameHeight: 189, frameCount: 28, imageWidth: 4536 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-magic_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,6,6,6,6], frameWidth: 74, frameHeight: 84, frameCount: 12, imageWidth: 888 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-magic_standby.png'),
        meta: { frameDelays: [9,9,9,9,9,9,9,9,9,9,9,9], frameWidth: 74, frameHeight: 83, frameCount: 12, imageWidth: 888 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-move.png'),
        meta: { frameDelays: [3], frameWidth: 72, frameHeight: 82, frameCount: 1, imageWidth: 72 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-standby.png'),
        meta: { frameDelays: [14,14,14,14,14,14,14,14,14,14,14,14], frameWidth: 76, frameHeight: 83, frameCount: 12, imageWidth: 912 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-win.png'),
        meta: { frameDelays: [9,9,9,9,9,9,9,9,9,9,9,9], frameWidth: 73, frameHeight: 86, frameCount: 12, imageWidth: 876 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Tilith/302000106-win_before.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,6,6,6,7,5,6,7,8,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9], frameWidth: 80, frameHeight: 90, frameCount: 33, imageWidth: 2640 },
      },
    },
  },
  Tressa: {
    characterId: 'Tressa',
    displayName: 'Tressa',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-atk.png'),
        meta: { frameDelays: [6,6,10,4,4,4,4,4,4,4,4,4,4,4,4,4,4], frameWidth: 203, frameHeight: 122, frameCount: 17, imageWidth: 3451 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-dead.png'),
        meta: { frameDelays: [6], frameWidth: 66, frameHeight: 39, frameCount: 1, imageWidth: 66 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-dying.png'),
        meta: { frameDelays: [6], frameWidth: 54, frameHeight: 43, frameCount: 1, imageWidth: 54 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-idle.png'),
        meta: { frameDelays: [8,8,8,8,8,8,8,8], frameWidth: 59, frameHeight: 74, frameCount: 8, imageWidth: 472 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-limit_atk.png'),
        meta: { frameDelays: [6,6,6,6,6,6,6,6,6,10,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,10,10,10,10,7], frameWidth: 403, frameHeight: 226, frameCount: 34, imageWidth: 13702 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-magic_atk.png'),
        meta: { frameDelays: [5,5,5,5], frameWidth: 74, frameHeight: 72, frameCount: 4, imageWidth: 296 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-magic_standby.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 70, frameHeight: 73, frameCount: 4, imageWidth: 280 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-move.png'),
        meta: { frameDelays: [4], frameWidth: 58, frameHeight: 65, frameCount: 1, imageWidth: 58 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-standby.png'),
        meta: { frameDelays: [5,5,5,5,5,5,5,5], frameWidth: 59, frameHeight: 73, frameCount: 8, imageWidth: 472 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-win.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 158, frameHeight: 72, frameCount: 4, imageWidth: 632 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Tressa/334000405-win_before.png'),
        meta: { frameDelays: [8,8,8,10,12,8,8,8,8,8,8,15,10,10,10,10], frameWidth: 194, frameHeight: 102, frameCount: 16, imageWidth: 3104 },
      },
    },
  },
  WOL: {
    characterId: 'WOL',
    displayName: 'Warrior of Light',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/WOL/201000407-atk.png'),
        meta: { frameDelays: [6,4,4,6,4,2,2,2,3,6,8,3,3,5,3,3,5,6,4,5,4,6,8,3,3,6,9,6,6,6,5,2,4,6,3,5], frameWidth: 234, frameHeight: 159, frameCount: 36, imageWidth: 8424 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/WOL/201000407-dead.png'),
        meta: { frameDelays: [4], frameWidth: 91, frameHeight: 47, frameCount: 1, imageWidth: 91 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/WOL/201000407-dying.png'),
        meta: { frameDelays: [4], frameWidth: 70, frameHeight: 70, frameCount: 1, imageWidth: 70 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/WOL/201000407-idle.png'),
        meta: { frameDelays: [14,11,14,11], frameWidth: 111, frameHeight: 115, frameCount: 4, imageWidth: 444 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/WOL/201000407-limit_atk.png'),
        meta: { frameDelays: [4,4,4,4,4,5,5,5,5,5,6,4,4,4,4,4,8,5,5,8,8], frameWidth: 555, frameHeight: 1084, frameCount: 21, imageWidth: 11655 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/WOL/201000407-magic_atk.png'),
        meta: { frameDelays: [7,7,7,7], frameWidth: 128, frameHeight: 115, frameCount: 4, imageWidth: 512 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/WOL/201000407-magic_standby.png'),
        meta: { frameDelays: [9,9,9,9], frameWidth: 97, frameHeight: 115, frameCount: 4, imageWidth: 388 },
      },
      move: {
        image: require('../../../assets/sprites/companions/WOL/201000407-move.png'),
        meta: { frameDelays: [4], frameWidth: 76, frameHeight: 85, frameCount: 1, imageWidth: 76 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/WOL/201000407-standby.png'),
        meta: { frameDelays: [14,14,14,14], frameWidth: 97, frameHeight: 115, frameCount: 4, imageWidth: 388 },
      },
      win: {
        image: require('../../../assets/sprites/companions/WOL/201000407-win.png'),
        meta: { frameDelays: [10,10,10,10], frameWidth: 71, frameHeight: 115, frameCount: 4, imageWidth: 284 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/WOL/201000407-win_before.png'),
        meta: { frameDelays: [8,6,8,8,6,6,6,6,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8], frameWidth: 171, frameHeight: 214, frameCount: 24, imageWidth: 4104 },
      },
    },
  },
  Yshtola: {
    characterId: 'Yshtola',
    displayName: 'Y\'shtola',
    animations: {
      atk: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-atk.png'),
        meta: { frameDelays: [3,4,4,5,5,5,4,4,5,5,5,5,5], frameWidth: 119, frameHeight: 80, frameCount: 13, imageWidth: 1547 },
      },
      dead: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-dead.png'),
        meta: { frameDelays: [4], frameWidth: 67, frameHeight: 32, frameCount: 1, imageWidth: 67 },
      },
      dying: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-dying.png'),
        meta: { frameDelays: [4], frameWidth: 56, frameHeight: 79, frameCount: 1, imageWidth: 56 },
      },
      idle: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-idle.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 78, frameHeight: 89, frameCount: 4, imageWidth: 312 },
      },
      limit_atk: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-limit_atk.png'),
        meta: { frameDelays: [5,5,5,5,5,5,5,5,5,5,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,5,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,6,6,7,7,8,7,6,6], frameWidth: 561, frameHeight: 455, frameCount: 74, imageWidth: 41514 },
      },
      magic_atk: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-magic_atk.png'),
        meta: { frameDelays: [4,4,4,4], frameWidth: 77, frameHeight: 91, frameCount: 4, imageWidth: 308 },
      },
      magic_standby: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-magic_standby.png'),
        meta: { frameDelays: [4,4,4,4,4,4,4,4], frameWidth: 82, frameHeight: 95, frameCount: 8, imageWidth: 656 },
      },
      move: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-move.png'),
        meta: { frameDelays: [4], frameWidth: 93, frameHeight: 66, frameCount: 1, imageWidth: 93 },
      },
      standby: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-standby.png'),
        meta: { frameDelays: [12,12,12,12], frameWidth: 84, frameHeight: 84, frameCount: 4, imageWidth: 336 },
      },
      win: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-win.png'),
        meta: { frameDelays: [16,16,16,16], frameWidth: 56, frameHeight: 79, frameCount: 4, imageWidth: 224 },
      },
      win_before: {
        image: require('../../../assets/sprites/companions/Yshtola/214000607-win_before.png'),
        meta: { frameDelays: [5,6,6,6,6,6,6,5,4,4,5,5,5,5,5,4,4,5,8,8], frameWidth: 119, frameHeight: 100, frameCount: 20, imageWidth: 2380 },
      },
    },
  },
};

export function getCharacterManifest(id: CharacterId): CharacterManifest {
  return SPRITE_REGISTRY[id];
}

export function hasAnim(id: CharacterId, anim: string): boolean {
  return anim in SPRITE_REGISTRY[id].animations;
}
