/**
 * CampaignDefinitions.ts — Static game data for the campaign system.
 *
 * Contains:
 * - 6 primary class definitions with full Rank 1-10 skill trees
 * - 6 secondary class definitions with 2 actives + 2 passives each
 * - Boss archetype mappings (expense category → boss)
 * - Main quest templates (chapter ladder)
 * - Side quest generators (expense-driven)
 *
 * All constants — never written to Firestore. Follows established pattern
 * from EXPEDITION_DEFINITIONS, SHOP_ITEMS, TOWN_BUILDING_DEFINITIONS.
 *
 * @see documentation/integration/EXPENSERPG.md §3, §5, §14-15
 */

import type {
  PrimaryClassDefinition,
  SecondaryClassDefinition,
  SkillDefinition,
  PassiveDefinition,
  BossArchetypeMapping,
  MainQuestTemplate,
  SideQuestGenerator,
  StatBlock,
  BossArchetype,
} from './CampaignTypes';
import { GEAR_ABILITIES } from './GearAbilityDefinitions';

// ═══════════════════════════════════════════════════════════════════════
// Helper — zero stat block
// ═══════════════════════════════════════════════════════════════════════

const ZERO_STATS: StatBlock = {
  strength: 0, defense: 0, speed: 0, health: 0, mana: 0, cdr: 0, precision: 0,
};

// ═══════════════════════════════════════════════════════════════════════
// PRIMARY CLASSES (6)
// ═══════════════════════════════════════════════════════════════════════

// ── VANGUARD (Tank/Warrior) ──────────────────────────────────────────

const VANGUARD_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  // Rank 1 — Basic Attack
  {
    id: 'vanguard_heavy_strike',
    classId: 'vanguard',
    name: 'Heavy Strike',
    description: 'STR-scaled single-target physical hit.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: null,
    baseValue: 20,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage'],
    ctCost: 10,
  },
  // Rank 2 — Passive: Iron Constitution
  {
    id: 'vanguard_iron_constitution',
    classId: 'vanguard',
    name: 'Iron Constitution',
    description: '+10% max HP.',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'health', type: 'percent', value: 0.10 }],
  },
  // Rank 3 — Active: Taunt
  {
    id: 'vanguard_taunt',
    classId: 'vanguard',
    name: 'Taunt',
    description: 'Force all enemies to target Vanguard for 2 turns.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 3,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'all_enemies',
    hitCount: 0,
    unlockRank: 3,
    effectTags: ['taunt'],
    ctCost: 12,
  },
  // Rank 4 — Passive: Battle Hardened
  {
    id: 'vanguard_battle_hardened',
    classId: 'vanguard',
    name: 'Battle Hardened',
    description: '+5% DEF for each enemy alive.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'defense', type: 'conditional', value: 0.05, condition: 'per_enemy_alive' }],
  },
  // Rank 5 — Active: War Cry
  {
    id: 'vanguard_war_cry',
    classId: 'vanguard',
    name: 'War Cry',
    description: 'ATK buff to all party members for 2 turns (+15% STR).',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 4,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'all_allies',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['buff'],
    ctCost: 14,
  },
  // Rank 6 — Passive: Second Wind
  {
    id: 'vanguard_second_wind',
    classId: 'vanguard',
    name: 'Second Wind',
    description: 'Heal 15% HP when dropping below 30% HP (1/battle).',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['heal'],
    modifiers: [{ target: 'self', property: 'hp', type: 'conditional', value: 0.15, condition: 'hp_below_30', triggerLimit: 1 }],
  },
  // Rank 7 — Active: Cleave
  {
    id: 'vanguard_cleave',
    classId: 'vanguard',
    name: 'Cleave',
    description: 'STR-scaled AoE hitting all enemies (0.7x multiplier).',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 5,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 0.7,
    targetType: 'all_enemies',
    hitCount: 1,
    unlockRank: 7,
    effectTags: ['damage'],
    ctCost: 16,
  },
  // Rank 8 — Passive: Fortify
  {
    id: 'vanguard_fortify',
    classId: 'vanguard',
    name: 'Fortify',
    description: '+8% damage reduction while HP > 50%.',
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'damage_reduction', type: 'conditional', value: 0.08, condition: 'hp_above_50' }],
  },
  // Rank 9 — Active: Unyielding Stand
  {
    id: 'vanguard_unyielding_stand',
    classId: 'vanguard',
    name: 'Unyielding Stand',
    description: 'Become immune to KO for 1 turn; reflect 20% damage taken.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 6,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0.20,
    targetType: 'self',
    hitCount: 0,
    unlockRank: 9,
    effectTags: ['ko_immunity', 'reflect'],
    ctCost: 18,
  },
  // Rank 10 — Passive: Unbreakable (Capstone)
  {
    id: 'vanguard_unbreakable',
    classId: 'vanguard',
    name: 'Unbreakable',
    description: 'When Vanguard is alive, party takes 10% less damage.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['buff'],
    modifiers: [{ target: 'party', property: 'damage_reduction', type: 'percent', value: 0.10 }],
  },
];

// ── ARCANIST (Mage) ──────────────────────────────────────────────────

const ARCANIST_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  {
    id: 'arcanist_arcane_bolt',
    classId: 'arcanist',
    name: 'Arcane Bolt',
    description: 'MANA-scaled single-target magic hit.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: null,
    baseValue: 10,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage'],
    ctCost: 10,
  },
  {
    id: 'arcanist_mana_well',
    classId: 'arcanist',
    name: 'Mana Well',
    description: '+15% max Mana.',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'mana', type: 'percent', value: 0.15 }],
  },
  {
    id: 'arcanist_fireball',
    classId: 'arcanist',
    name: 'Fireball',
    description: 'MANA-scaled AoE magic damage (all enemies, 0.8x).',
    skillType: 'active',
    costType: 'mana',
    manaCost: 30,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: null,
    baseValue: 12,
    skillMultiplier: 0.8,
    targetType: 'all_enemies',
    hitCount: 1,
    unlockRank: 3,
    effectTags: ['damage'],
    ctCost: 14,
  },
  {
    id: 'arcanist_spell_focus',
    classId: 'arcanist',
    name: 'Spell Focus',
    description: '+10% magic damage when Mana > 50%.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'magic_damage', type: 'conditional', value: 0.10, condition: 'mana_above_50' }],
  },
  {
    id: 'arcanist_mana_shield',
    classId: 'arcanist',
    name: 'Mana Shield',
    description: 'Convert next incoming damage to Mana cost instead of HP (1 hit).',
    skillType: 'active',
    costType: 'mana',
    manaCost: 20,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'self',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['shield'],
    ctCost: 12,
  },
  {
    id: 'arcanist_arcane_efficiency',
    classId: 'arcanist',
    name: 'Arcane Efficiency',
    description: '-10% Mana cost on all active skills.',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'mana_cost', type: 'percent', value: -0.10 }],
  },
  {
    id: 'arcanist_chain_lightning',
    classId: 'arcanist',
    name: 'Chain Lightning',
    description: 'Hit primary target (1.0x), then bounce to 2 additional enemies (0.5x each).',
    skillType: 'active',
    costType: 'mana',
    manaCost: 40,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: null,
    baseValue: 15,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 3,
    unlockRank: 7,
    effectTags: ['damage'],
    ctCost: 16,
  },
  {
    id: 'arcanist_overcharge',
    classId: 'arcanist',
    name: 'Overcharge',
    description: 'Crits restore 15% Mana spent on the triggering skill.',
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'mana_restore_on_crit', type: 'percent', value: 0.15 }],
  },
  {
    id: 'arcanist_meteor',
    classId: 'arcanist',
    name: 'Meteor',
    description: 'Massive AoE (all enemies, 1.5x MANA-scaled). Highest damage skill.',
    skillType: 'active',
    costType: 'mana',
    manaCost: 60,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: null,
    baseValue: 25,
    skillMultiplier: 1.5,
    targetType: 'all_enemies',
    hitCount: 1,
    unlockRank: 9,
    effectTags: ['damage'],
    ctCost: 20,
  },
  {
    id: 'arcanist_arcane_mastery',
    classId: 'arcanist',
    name: 'Arcane Mastery',
    description: 'All Arcanist skills gain +20% damage; Mana regen +3/turn.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['buff'],
    modifiers: [
      { target: 'self', property: 'class_damage', type: 'percent', value: 0.20 },
      { target: 'self', property: 'mana_regen', type: 'flat', value: 3 },
    ],
  },
];

// ── RANGER (Fast DPS) ────────────────────────────────────────────────

const RANGER_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  {
    id: 'ranger_quick_shot',
    classId: 'ranger',
    name: 'Quick Shot',
    description: 'SPD-scaled single-target physical hit.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage'],
    ctCost: 10,
  },
  {
    id: 'ranger_fleet_footed',
    classId: 'ranger',
    name: 'Fleet Footed',
    description: '+10% SPD (faster CT recharge).',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'speed', type: 'percent', value: 0.10 }],
  },
  {
    id: 'ranger_aimed_shot',
    classId: 'ranger',
    name: 'Aimed Shot',
    description: 'High single-target damage (1.5x), +25% crit chance.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 3,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: 'strength',
    baseValue: 12,
    skillMultiplier: 1.5,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 3,
    effectTags: ['damage'],
    ctCost: 14,
  },
  {
    id: 'ranger_eagle_eye',
    classId: 'ranger',
    name: 'Eagle Eye',
    description: '+10% base crit chance.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'crit_chance', type: 'flat', value: 0.10 }],
  },
  {
    id: 'ranger_evasion',
    classId: 'ranger',
    name: 'Evasion',
    description: 'Dodge all attacks for 1 turn.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 4,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'self',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['dodge'],
    ctCost: 12,
  },
  {
    id: 'ranger_quick_draw',
    classId: 'ranger',
    name: 'Quick Draw',
    description: 'First action each battle has -1 CT cost (acts sooner).',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'first_action_ct', type: 'flat', value: -1 }],
  },
  {
    id: 'ranger_rapid_fire',
    classId: 'ranger',
    name: 'Rapid Fire',
    description: '3 hits at 0.5x each on random enemies.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 5,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: null,
    baseValue: 6,
    skillMultiplier: 0.5,
    targetType: 'random_enemies',
    hitCount: 3,
    unlockRank: 7,
    effectTags: ['damage'],
    ctCost: 16,
  },
  {
    id: 'ranger_predators_instinct',
    classId: 'ranger',
    name: "Predator's Instinct",
    description: 'Crit damage +30% (base crit damage is 1.5x → becomes 1.8x).',
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'crit_damage', type: 'flat', value: 0.30 }],
  },
  {
    id: 'ranger_lethal_volley',
    classId: 'ranger',
    name: 'Lethal Volley',
    description: 'Single-target 2.0x damage. Guaranteed crit if target HP < 30%.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 6,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: 'strength',
    baseValue: 18,
    skillMultiplier: 2.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 9,
    effectTags: ['damage'],
    ctCost: 18,
  },
  {
    id: 'ranger_apex_hunter',
    classId: 'ranger',
    name: 'Apex Hunter',
    description: 'After any kill, Ranger immediately gains a bonus turn.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'bonus_turn_on_kill', type: 'flat', value: 1 }],
  },
];

// ── CLERIC (Healer/Support) ─────────────────────────────────────────

const CLERIC_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  {
    id: 'cleric_smite',
    classId: 'cleric',
    name: 'Smite',
    description: 'HP-scaled single-target holy damage.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'health',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 0.8,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage'],
    ctCost: 10,
  },
  {
    id: 'cleric_inner_light',
    classId: 'cleric',
    name: 'Inner Light',
    description: '+5 Mana regen per turn.',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'mana_regen', type: 'flat', value: 5 }],
  },
  {
    id: 'cleric_heal',
    classId: 'cleric',
    name: 'Heal',
    description: 'Restore 30% of target ally\'s max HP.',
    skillType: 'active',
    costType: 'mana',
    manaCost: 25,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'health',
    secondaryScalingStat: 'mana',
    baseValue: 0,
    skillMultiplier: 0.30,
    targetType: 'single_ally',
    hitCount: 1,
    unlockRank: 3,
    effectTags: ['heal'],
    ctCost: 12,
  },
  {
    id: 'cleric_blessed_aura',
    classId: 'cleric',
    name: 'Blessed Aura',
    description: 'Party HP regen +2% max HP per turn.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['hot'],
    modifiers: [{ target: 'party', property: 'hp_regen', type: 'percent', value: 0.02 }],
  },
  {
    id: 'cleric_bless',
    classId: 'cleric',
    name: 'Bless',
    description: 'Target ally gains +15% STR, +15% DEF for 3 turns.',
    skillType: 'active',
    costType: 'mana',
    manaCost: 20,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'single_ally',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['buff'],
    ctCost: 12,
  },
  {
    id: 'cleric_purity',
    classId: 'cleric',
    name: 'Purity',
    description: 'Cleric is immune to debuffs.',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'debuff_immunity', type: 'flat', value: 1 }],
  },
  {
    id: 'cleric_sanctuary',
    classId: 'cleric',
    name: 'Sanctuary',
    description: "All party members gain a shield equal to 20% Cleric's max HP for 2 turns.",
    skillType: 'active',
    costType: 'mana',
    manaCost: 40,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'health',
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0.20,
    targetType: 'all_allies',
    hitCount: 0,
    unlockRank: 7,
    effectTags: ['shield'],
    ctCost: 16,
  },
  {
    id: 'cleric_martyrs_grace',
    classId: 'cleric',
    name: "Martyr's Grace",
    description: "When an ally would be KO'd, Cleric auto-heals them for 25% HP (1/battle).",
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['heal'],
    modifiers: [{ target: 'party', property: 'prevent_ko_heal', type: 'percent', value: 0.25, triggerLimit: 1 }],
  },
  {
    id: 'cleric_revive',
    classId: 'cleric',
    name: 'Revive',
    description: "Bring a KO'd ally back with 40% HP.",
    skillType: 'active',
    costType: 'mana',
    manaCost: 50,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0.40,
    targetType: 'single_ally',
    hitCount: 0,
    unlockRank: 9,
    effectTags: ['revive'],
    ctCost: 18,
  },
  {
    id: 'cleric_divine_providence',
    classId: 'cleric',
    name: 'Divine Providence',
    description: 'All healing effects +30%; Revive cooldown -2 turns.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['buff'],
    modifiers: [
      { target: 'self', property: 'healing_bonus', type: 'percent', value: 0.30 },
      { target: 'self', property: 'revive_cdr', type: 'flat', value: 2 },
    ],
  },
];

// ── ROGUE (Utility/Debuff) ──────────────────────────────────────────

const ROGUE_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  {
    id: 'rogue_backstab',
    classId: 'rogue',
    name: 'Backstab',
    description: 'SPD-scaled single-target. +50% damage if attacker has higher SPD than target.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: null,
    baseValue: 9,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage'],
    ctCost: 10,
  },
  {
    id: 'rogue_shadow_step',
    classId: 'rogue',
    name: 'Shadow Step',
    description: '+15% dodge chance.',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['dodge'],
    modifiers: [{ target: 'self', property: 'dodge_chance', type: 'flat', value: 0.15 }],
  },
  {
    id: 'rogue_poison_blade',
    classId: 'rogue',
    name: 'Poison Blade',
    description: 'Deal damage + apply Poison (5% HP/turn for 3 turns).',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 3,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 0.8,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 3,
    effectTags: ['damage', 'dot'],
    tickConfig: {
      dot: { value: 0.05, durationTurns: 3, subtype: 'poison' },
    },
    ctCost: 12,
  },
  {
    id: 'rogue_opportunist',
    classId: 'rogue',
    name: 'Opportunist',
    description: '+20% damage against debuffed enemies.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'damage_vs_debuffed', type: 'percent', value: 0.20 }],
  },
  {
    id: 'rogue_smoke_bomb',
    classId: 'rogue',
    name: 'Smoke Bomb',
    description: 'All enemies: -25% accuracy for 2 turns.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 4,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'all_enemies',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['debuff'],
    ctCost: 12,
  },
  {
    id: 'rogue_nimble_fingers',
    classId: 'rogue',
    name: 'Nimble Fingers',
    description: 'CDR +5% (stacks with base stat).',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'cdr', type: 'flat', value: 0.05 }],
  },
  {
    id: 'rogue_pilfer',
    classId: 'rogue',
    name: 'Pilfer',
    description: 'Steal a random buff from target enemy. If no buffs, steal 10% gold reward.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 5,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'single_enemy',
    hitCount: 0,
    unlockRank: 7,
    effectTags: ['steal', 'dispel'],
    ctCost: 14,
  },
  {
    id: 'rogue_vanish',
    classId: 'rogue',
    name: 'Vanish',
    description: 'After using a skill, 20% chance to become untargetable for 1 turn.',
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['dodge'],
    modifiers: [{ target: 'self', property: 'vanish_chance', type: 'percent', value: 0.20 }],
  },
  {
    id: 'rogue_assassinate',
    classId: 'rogue',
    name: 'Assassinate',
    description: '2.5x damage to single target. Costs 15% of Rogue\'s current HP.',
    skillType: 'active',
    costType: 'mixed',
    manaCost: 0,
    cooldownTurns: 6,
    hpCostPct: 0.15,
    scalingStat: 'speed',
    secondaryScalingStat: 'strength',
    baseValue: 20,
    skillMultiplier: 2.5,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 9,
    effectTags: ['damage'],
    ctCost: 18,
  },
  {
    id: 'rogue_master_of_shadows',
    classId: 'rogue',
    name: 'Master of Shadows',
    description: 'All Rogue cooldowns -1 turn; Poison duration +1 turn.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['buff'],
    modifiers: [
      { target: 'self', property: 'class_cdr', type: 'flat', value: 1 },
      { target: 'self', property: 'poison_duration', type: 'flat', value: 1 },
    ],
  },
];

// ── WARDEN (Defensive Support) ──────────────────────────────────────

const WARDEN_SKILLS: (SkillDefinition | PassiveDefinition)[] = [
  {
    id: 'warden_shield_bash',
    classId: 'warden',
    name: 'Shield Bash',
    description: 'DEF-scaled single-target. 15% chance to stun for 1 turn.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'defense',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 0.9,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 1,
    effectTags: ['damage', 'stun'],
    ctCost: 10,
  },
  {
    id: 'warden_bulwark',
    classId: 'warden',
    name: 'Bulwark',
    description: '+10% DEF.',
    skillType: 'passive',
    unlockRank: 2,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'defense', type: 'percent', value: 0.10 }],
  },
  {
    id: 'warden_barrier',
    classId: 'warden',
    name: 'Barrier',
    description: "Grant target ally a shield equal to 25% of Warden's DEF for 3 turns.",
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 3,
    hpCostPct: 0,
    scalingStat: 'defense',
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0.25,
    targetType: 'single_ally',
    hitCount: 0,
    unlockRank: 3,
    effectTags: ['shield'],
    ctCost: 12,
  },
  {
    id: 'warden_stone_skin',
    classId: 'warden',
    name: 'Stone Skin',
    description: 'Reduce all incoming damage by flat 5%.',
    skillType: 'passive',
    unlockRank: 4,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'damage_reduction', type: 'percent', value: 0.05 }],
  },
  {
    id: 'warden_iron_wall',
    classId: 'warden',
    name: 'Iron Wall',
    description: 'Warden takes 50% reduced damage for 2 turns.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 4,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0.50,
    targetType: 'self',
    hitCount: 0,
    unlockRank: 5,
    effectTags: ['buff'],
    ctCost: 12,
  },
  {
    id: 'warden_guardians_resolve',
    classId: 'warden',
    name: "Guardian's Resolve",
    description: 'When any ally drops below 50% HP, Warden gains +10% DEF (stacks 3x).',
    skillType: 'passive',
    unlockRank: 6,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'defense', type: 'conditional', value: 0.10, condition: 'ally_hp_below_50', maxStacks: 3 }],
  },
  {
    id: 'warden_guardian_aura',
    classId: 'warden',
    name: 'Guardian Aura',
    description: 'All party members gain +10% DEF for 3 turns.',
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 5,
    hpCostPct: 0,
    scalingStat: null,
    secondaryScalingStat: null,
    baseValue: 0,
    skillMultiplier: 0,
    targetType: 'all_allies',
    hitCount: 0,
    unlockRank: 7,
    effectTags: ['buff'],
    ctCost: 14,
  },
  {
    id: 'warden_absorb',
    classId: 'warden',
    name: 'Absorb',
    description: 'Shields (from any source) on Warden are 25% more effective.',
    skillType: 'passive',
    unlockRank: 8,
    effectTags: ['buff'],
    modifiers: [{ target: 'self', property: 'shield_effectiveness', type: 'percent', value: 0.25 }],
  },
  {
    id: 'warden_bastion',
    classId: 'warden',
    name: 'Bastion',
    description: "Create a party-wide shield equal to 30% of Warden's max HP. Lasts 2 turns or until broken.",
    skillType: 'active',
    costType: 'cooldown',
    manaCost: 0,
    cooldownTurns: 6,
    hpCostPct: 0,
    scalingStat: 'health',
    secondaryScalingStat: 'defense',
    baseValue: 0,
    skillMultiplier: 0.30,
    targetType: 'all_allies',
    hitCount: 0,
    unlockRank: 9,
    effectTags: ['shield'],
    ctCost: 18,
  },
  {
    id: 'warden_immovable',
    classId: 'warden',
    name: 'Immovable',
    description: 'Warden cannot be killed in a single hit (survives with 1 HP). Party shields decay 1 turn slower.',
    skillType: 'passive',
    unlockRank: 10,
    effectTags: ['ko_immunity', 'buff'],
    modifiers: [
      { target: 'self', property: 'one_hit_protection', type: 'flat', value: 1 },
      { target: 'party', property: 'shield_duration', type: 'flat', value: 1 },
    ],
  },
];

// ── PRIMARY CLASS DEFINITIONS ARRAY ─────────────────────────────────

export const PRIMARY_CLASS_DEFINITIONS: PrimaryClassDefinition[] = [
  {
    id: 'vanguard',
    name: 'Vanguard',
    description: 'Front-line anchor. High survivability, moderate damage. The group\'s wall.',
    statBias: { primary: 'strength', secondary: 'health' },
    costBias: 'cooldown',
    baselineStats: { strength: 14, defense: 10, speed: 6, health: 18, mana: 4, cdr: 2, precision: 7 },
    skills: VANGUARD_SKILLS,
  },
  {
    id: 'arcanist',
    name: 'Arcanist',
    description: 'Burst caster. AoE damage, resource management. Glass cannon with utility.',
    statBias: { primary: 'mana', secondary: 'cdr' },
    costBias: 'mana',
    baselineStats: { strength: 4, defense: 5, speed: 8, health: 10, mana: 22, cdr: 5, precision: 11 },
    skills: ARCANIST_SKILLS,
  },
  {
    id: 'ranger',
    name: 'Ranger',
    description: 'Fastest turns, highest crit rate, single-target specialist. Hit and run.',
    statBias: { primary: 'speed', secondary: 'strength' },
    costBias: 'cooldown',
    baselineStats: { strength: 10, defense: 6, speed: 18, health: 12, mana: 4, cdr: 4, precision: 14 },
    skills: RANGER_SKILLS,
  },
  {
    id: 'cleric',
    name: 'Cleric',
    description: 'Party sustain, healing, buffs, revival. The group\'s lifeline.',
    statBias: { primary: 'health', secondary: 'mana' },
    costBias: 'mana',
    baselineStats: { strength: 5, defense: 8, speed: 6, health: 18, mana: 16, cdr: 3, precision: 8 },
    skills: CLERIC_SKILLS,
  },
  {
    id: 'rogue',
    name: 'Rogue',
    description: 'Fastest turns, debuffs, steal mechanics. Disrupts enemies, finds advantages.',
    statBias: { primary: 'speed', secondary: 'cdr' },
    costBias: 'mixed',
    baselineStats: { strength: 8, defense: 5, speed: 18, health: 10, mana: 6, cdr: 7, precision: 12 },
    skills: ROGUE_SKILLS,
  },
  {
    id: 'warden',
    name: 'Warden',
    description: 'Shields, damage reduction, party protection. Financial stability embodied.',
    statBias: { primary: 'defense', secondary: 'health' },
    costBias: 'cooldown',
    baselineStats: { strength: 6, defense: 18, speed: 5, health: 16, mana: 4, cdr: 3, precision: 9 },
    skills: WARDEN_SKILLS,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// SECONDARY CLASSES (6)
// ═══════════════════════════════════════════════════════════════════════

export const SECONDARY_CLASS_DEFINITIONS: SecondaryClassDefinition[] = [
  // ── TACTICIAN ─────────────────────────────────────────────────────
  {
    id: 'tactician',
    name: 'Tactician',
    description: 'Party buffs + enemy debuffs.',
    focus: 'Party buffs + enemy debuffs',
    skills: [
      {
        id: 'tactician_rally',
        classId: 'tactician',
        name: 'Rally',
        description: 'All allies: +15% ATK for 2 turns.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 4,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0,
        targetType: 'all_allies',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['buff'],
        ctCost: 14,
      },
      {
        id: 'tactician_analyze',
        classId: 'tactician',
        name: 'Analyze',
        description: 'Target enemy: -20% DEF for 3 turns. Reveals enemy stats.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0,
        targetType: 'single_enemy',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['debuff'],
        ctCost: 12,
      },
      {
        id: 'tactician_formation',
        classId: 'tactician',
        name: 'Formation',
        description: 'Party SPD +5%.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'party', property: 'speed', type: 'percent', value: 0.05 }],
      },
      {
        id: 'tactician_exploit_weakness',
        classId: 'tactician',
        name: 'Exploit Weakness',
        description: '+15% crit chance against debuffed enemies.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'crit_vs_debuffed', type: 'conditional', value: 0.15, condition: 'target_has_debuff' }],
      },
    ],
  },
  // ── ALCHEMIST ─────────────────────────────────────────────────────
  {
    id: 'alchemist',
    name: 'Alchemist',
    description: 'Healing over time, temporary stat boosts.',
    focus: 'Healing over time, temporary stat boosts',
    skills: [
      {
        id: 'alchemist_healing_salve',
        classId: 'alchemist',
        name: 'Healing Salve',
        description: 'Target ally: heal 8% max HP/turn for 3 turns.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 10,
        skillMultiplier: 0.08,
        targetType: 'single_ally',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['hot'],
        tickConfig: {
          hot: { value: 0.08, durationTurns: 3, subtype: 'regen' },
        },
        ctCost: 12,
      },
      {
        id: 'alchemist_elixir',
        classId: 'alchemist',
        name: 'Elixir',
        description: "Target ally: +20% to their highest stat for 3 turns.",
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 4,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0.20,
        targetType: 'single_ally',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['buff'],
        ctCost: 14,
      },
      {
        id: 'alchemist_brew_master',
        classId: 'alchemist',
        name: 'Brew Master',
        description: 'All HoT effects +25% potency.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'hot_potency', type: 'percent', value: 0.25 }],
      },
      {
        id: 'alchemist_volatile_mix',
        classId: 'alchemist',
        name: 'Volatile Mix',
        description: '20% chance Elixir also applies to adjacent party members.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'elixir_spread_chance', type: 'percent', value: 0.20 }],
      },
    ],
  },
  // ── DUELIST ───────────────────────────────────────────────────────
  {
    id: 'duelist',
    name: 'Duelist',
    description: 'Counter-attacks and riposte.',
    focus: 'Counter-attacks and riposte',
    skills: [
      {
        id: 'duelist_parry',
        classId: 'duelist',
        name: 'Parry',
        description: 'Counter the next physical attack for 1.5x damage.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: 'strength',
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 1.5,
        targetType: 'self',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['counter'],
        ctCost: 12,
      },
      {
        id: 'duelist_riposte_stance',
        classId: 'duelist',
        name: 'Riposte Stance',
        description: 'For 2 turns, auto-counter every attack (0.5x damage each).',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 5,
        hpCostPct: 0,
        scalingStat: 'strength',
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0.5,
        targetType: 'self',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['counter'],
        ctCost: 14,
      },
      {
        id: 'duelist_first_blood',
        classId: 'duelist',
        name: 'First Blood',
        description: '+20% damage on first attack of battle.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'first_attack_damage', type: 'percent', value: 0.20, triggerLimit: 1 }],
      },
      {
        id: 'duelist_en_garde',
        classId: 'duelist',
        name: 'En Garde',
        description: 'Free counter-attack once per battle (triggers automatically).',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['counter'],
        modifiers: [{ target: 'self', property: 'free_counter', type: 'flat', value: 1, triggerLimit: 1 }],
      },
    ],
  },
  // ── ENCHANTER ─────────────────────────────────────────────────────
  {
    id: 'enchanter',
    name: 'Enchanter',
    description: 'Elemental damage overlay + dispel.',
    focus: 'Elemental damage overlay + dispel',
    skills: [
      {
        id: 'enchanter_imbue_element',
        classId: 'enchanter',
        name: 'Imbue Element',
        description: "Target ally's next 3 attacks deal +30% bonus elemental damage.",
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 4,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0.30,
        targetType: 'single_ally',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['buff'],
        ctCost: 14,
      },
      {
        id: 'enchanter_dispel',
        classId: 'enchanter',
        name: 'Dispel',
        description: 'Remove all buffs from target enemy.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0,
        targetType: 'single_enemy',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['dispel'],
        ctCost: 12,
      },
      {
        id: 'enchanter_resonance',
        classId: 'enchanter',
        name: 'Resonance',
        description: '+10% damage when attacking with matching element advantage.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'elemental_damage', type: 'conditional', value: 0.10, condition: 'element_advantage' }],
      },
      {
        id: 'enchanter_mana_siphon',
        classId: 'enchanter',
        name: 'Mana Siphon',
        description: 'Kills restore 10% max Mana to the killer.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'mana_restore_on_kill', type: 'percent', value: 0.10 }],
      },
    ],
  },
  // ── SENTINEL ──────────────────────────────────────────────────────
  {
    id: 'sentinel',
    name: 'Sentinel',
    description: 'Aggro management + damage redirect.',
    focus: 'Aggro management + damage redirect',
    skills: [
      {
        id: 'sentinel_intercept',
        classId: 'sentinel',
        name: 'Intercept',
        description: 'Take the next hit aimed at target ally.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0,
        targetType: 'single_ally',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['taunt'],
        ctCost: 12,
      },
      {
        id: 'sentinel_provoke',
        classId: 'sentinel',
        name: 'Provoke',
        description: 'Force target enemy to attack Sentinel for 2 turns.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 4,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0,
        targetType: 'single_enemy',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['taunt'],
        ctCost: 14,
      },
      {
        id: 'sentinel_steadfast',
        classId: 'sentinel',
        name: 'Steadfast',
        description: '-10% damage taken while a guard/intercept effect is active.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'damage_reduction', type: 'conditional', value: 0.10, condition: 'guard_active' }],
      },
      {
        id: 'sentinel_last_stand',
        classId: 'sentinel',
        name: 'Last Stand',
        description: '+20% DEF when HP drops below 25%.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['buff'],
        modifiers: [{ target: 'self', property: 'defense', type: 'conditional', value: 0.20, condition: 'hp_below_25' }],
      },
    ],
  },
  // ── HARBINGER ─────────────────────────────────────────────────────
  {
    id: 'harbinger',
    name: 'Harbinger',
    description: 'DoT + debuffs over time.',
    focus: 'DoT + debuffs over time',
    skills: [
      {
        id: 'harbinger_curse',
        classId: 'harbinger',
        name: 'Curse',
        description: 'Target enemy: DoT (4% HP/turn) + SPD -15% for 3 turns.',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 3,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0.04,
        targetType: 'single_enemy',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['dot', 'debuff'],
        tickConfig: {
          dot: { value: 0.04, durationTurns: 3, subtype: 'poison' },
        },
        ctCost: 12,
      },
      {
        id: 'harbinger_wither',
        classId: 'harbinger',
        name: 'Wither',
        description: 'Target enemy: DEF -10%/turn for 3 turns (cumulative).',
        skillType: 'active',
        costType: 'cooldown',
        manaCost: 0,
        cooldownTurns: 4,
        hpCostPct: 0,
        scalingStat: null,
        secondaryScalingStat: null,
        baseValue: 0,
        skillMultiplier: 0.10,
        targetType: 'single_enemy',
        hitCount: 0,
        unlockRank: 0,
        effectTags: ['debuff'],
        ctCost: 14,
      },
      {
        id: 'harbinger_spreading_plague',
        classId: 'harbinger',
        name: 'Spreading Plague',
        description: 'When a DoT-affected enemy dies, DoT spreads to nearest enemy.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['dot'],
        modifiers: [{ target: 'enemies', property: 'dot_spread_on_death', type: 'flat', value: 1 }],
      },
      {
        id: 'harbinger_dread_aura',
        classId: 'harbinger',
        name: 'Dread Aura',
        description: 'All enemies: -5% crit chance.',
        skillType: 'passive',
        unlockRank: 0,
        effectTags: ['debuff'],
        modifiers: [{ target: 'enemies', property: 'crit_chance', type: 'flat', value: -0.05 }],
      },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════
// BOSS ARCHETYPE MAPPINGS
// ═══════════════════════════════════════════════════════════════════════

export const BOSS_ARCHETYPE_MAPPINGS: BossArchetypeMapping[] = [
  { expenseCategory: 'Food & Dining', archetype: 'the_gourmand', namePattern: 'Glutton of {source}', visualFlavor: 'Rotund beast with utensils' },
  { expenseCategory: 'Transport', archetype: 'the_road_warden', namePattern: 'Toll Keeper of {source}', visualFlavor: 'Armored roadblock creature' },
  { expenseCategory: 'Entertainment', archetype: 'the_revelmaster', namePattern: 'Lord of Spectacles', visualFlavor: 'Jester/carnival creature' },
  { expenseCategory: 'Shopping', archetype: 'the_hoarder', namePattern: 'Collector of {source}', visualFlavor: 'Dragon on treasure pile' },
  { expenseCategory: 'Utilities', archetype: 'the_siphon', namePattern: 'Drain of {source}', visualFlavor: 'Energy parasite' },
  { expenseCategory: 'Rent/Housing', archetype: 'the_landlord', namePattern: 'Keeper of the Keep', visualFlavor: 'Castle guardian' },
  { expenseCategory: 'Travel', archetype: 'the_wanderer', namePattern: 'Vagrant of {source}', visualFlavor: 'Nomadic giant' },
  { expenseCategory: 'Healthcare', archetype: 'the_plague_lord', namePattern: 'Blight of the Ward', visualFlavor: 'Pestilence creature' },
  { expenseCategory: 'Other', archetype: 'the_anomaly', namePattern: 'Unknown Entity', visualFlavor: 'Shifting shadow' },
];

/** Split type → boss trait mapping */
export const SPLIT_TYPE_TO_TRAIT: Record<string, string> = {
  EQUAL: 'balanced',
  PERCENTAGE: 'cunning',
  SHARES: 'greedy',
  EXACT: 'precise',
};

// ═══════════════════════════════════════════════════════════════════════
// MAIN QUEST TEMPLATES (chapter ladder)
// ═══════════════════════════════════════════════════════════════════════

export const MAIN_QUEST_TEMPLATES: MainQuestTemplate[] = [
  { chapter: 1, title: 'The First Reckoning', description: 'Your campaign begins. Defeat the first boss to prove your worth.', difficulty: 1, requiredBossesDefeated: 0, encounterCount: 1, rewardScale: 1.0 },
  { chapter: 2, title: 'Gathering Strength', description: 'The path grows harder. Two encounters stand between you and the next boss.', difficulty: 2, requiredBossesDefeated: 0, encounterCount: 2, rewardScale: 1.2 },
  { chapter: 3, title: 'The Debt Collector', description: 'A powerful entity demands tribute. Three encounters guard the way.', difficulty: 3, requiredBossesDefeated: 0, encounterCount: 2, rewardScale: 1.4 },
  { chapter: 4, title: 'Into the Ledger', description: 'The campaign deepens. Stronger foes await within the ancient records.', difficulty: 4, requiredBossesDefeated: 0, encounterCount: 3, rewardScale: 1.6 },
  { chapter: 5, title: 'The Rival Emerges', description: 'A nemesis born from your own spending habits. Can you overcome yourself?', difficulty: 5, requiredBossesDefeated: 0, encounterCount: 4, rewardScale: 1.8 },
  { chapter: 6, title: 'Breaking Even', description: 'Balance the books — or be consumed by the imbalance.', difficulty: 6, requiredBossesDefeated: 0, encounterCount: 5, rewardScale: 2.0 },
  { chapter: 7, title: 'The Audit Trail', description: 'Every receipt tells a story. Follow the trail to its source.', difficulty: 7, requiredBossesDefeated: 0, encounterCount: 6, rewardScale: 2.2 },
  { chapter: 8, title: 'Settlement Day', description: 'The ultimate reckoning. All debts come due.', difficulty: 8, requiredBossesDefeated: 0, encounterCount: 7, rewardScale: 2.5 },
];

// ═══════════════════════════════════════════════════════════════════════
// SIDE QUEST GENERATORS
// ═══════════════════════════════════════════════════════════════════════

export const SIDE_QUEST_GENERATORS: SideQuestGenerator[] = [
  { triggerCategory: 'Food & Dining', titlePattern: 'Pantry Raid', descriptionPattern: 'Clear out the kitchen creatures from {source}.', difficultyRange: { min: 1, max: 3 }, rewardScale: 0.6 },
  { triggerCategory: 'Transport', titlePattern: 'Toll Road Patrol', descriptionPattern: 'Secure the road from {source}.', difficultyRange: { min: 1, max: 4 }, rewardScale: 0.6 },
  { triggerCategory: 'Entertainment', titlePattern: 'Carnival Cleanup', descriptionPattern: 'The show must go on — after you clear the stage.', difficultyRange: { min: 1, max: 3 }, rewardScale: 0.5 },
  { triggerCategory: 'Shopping', titlePattern: 'Bargain Hunt', descriptionPattern: 'Track down the deals before they disappear.', difficultyRange: { min: 1, max: 4 }, rewardScale: 0.7 },
  { triggerCategory: 'Utilities', titlePattern: 'Power Surge', descriptionPattern: 'Something is draining the energy. Investigate.', difficultyRange: { min: 2, max: 5 }, rewardScale: 0.7 },
  { triggerCategory: 'Rent/Housing', titlePattern: 'Dungeon Inspection', descriptionPattern: 'The landlord needs the basement cleared. Again.', difficultyRange: { min: 2, max: 5 }, rewardScale: 0.8 },
  { triggerCategory: 'Travel', titlePattern: 'Wanderer\'s Errand', descriptionPattern: 'A traveler needs escort through dangerous territory.', difficultyRange: { min: 2, max: 6 }, rewardScale: 0.8 },
  { triggerCategory: 'Healthcare', titlePattern: 'Remedy Fetch', descriptionPattern: 'Gather ingredients for a crucial antidote.', difficultyRange: { min: 1, max: 4 }, rewardScale: 0.6 },
];

// ═══════════════════════════════════════════════════════════════════════
// LOOKUP HELPERS
// ═══════════════════════════════════════════════════════════════════════

/** Lookup a primary class by ID. */
export function getPrimaryClass(id: string): PrimaryClassDefinition | undefined {
  return PRIMARY_CLASS_DEFINITIONS.find(c => c.id === id);
}

/** Lookup a secondary class by ID. */
export function getSecondaryClass(id: string): SecondaryClassDefinition | undefined {
  return SECONDARY_CLASS_DEFINITIONS.find(c => c.id === id);
}

/** Get all skills (active + passive) for a primary class up to a given rank. */
export function getUnlockedSkills(classId: string, rank: number): (SkillDefinition | PassiveDefinition)[] {
  const cls = getPrimaryClass(classId);
  if (!cls) return [];
  return cls.skills.filter(s => s.unlockRank <= rank);
}

/**
 * Enemy attack skills — one per boss archetype + a generic fallback.
 * These are basic single-target physical attacks with archetype-flavored stats.
 */
const ENEMY_SKILLS: SkillDefinition[] = [
  // Generic (main quest encounters)
  {
    id: 'enemy_attack_generic',
    classId: 'warrior' as any,
    name: 'Attack',
    description: 'Basic enemy attack.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 50,
  },
  // Boss archetypes
  {
    id: 'enemy_attack_the_gourmand',
    classId: 'warrior' as any,
    name: 'Devour',
    description: 'A crushing bite.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: 'health',
    baseValue: 10,
    skillMultiplier: 1.1,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 12,
  },
  {
    id: 'enemy_attack_the_road_warden',
    classId: 'warrior' as any,
    name: 'Toll Strike',
    description: 'Armored slam.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: 'defense',
    baseValue: 10,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 11,
  },
  {
    id: 'enemy_attack_the_revelmaster',
    classId: 'warrior' as any,
    name: 'Wild Show',
    description: 'Chaotic spectacle.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: null,
    baseValue: 8,
    skillMultiplier: 1.1,
    targetType: 'single_enemy',
    hitCount: 2,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 9,
  },
  {
    id: 'enemy_attack_the_hoarder',
    classId: 'warrior' as any,
    name: 'Treasure Slam',
    description: 'Heavy treasure barrage.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: 'defense',
    baseValue: 12,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 13,
  },
  {
    id: 'enemy_attack_the_siphon',
    classId: 'warrior' as any,
    name: 'Drain Pulse',
    description: 'Energy-draining bolt.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: null,
    baseValue: 9,
    skillMultiplier: 1.1,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 9,
  },
  {
    id: 'enemy_attack_the_landlord',
    classId: 'warrior' as any,
    name: 'Eviction Notice',
    description: 'Forceful push.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: 'defense',
    baseValue: 10,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 11,
  },
  {
    id: 'enemy_attack_the_wanderer',
    classId: 'warrior' as any,
    name: 'Nomad Strike',
    description: 'Swift wanderer blow.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'speed',
    secondaryScalingStat: 'strength',
    baseValue: 9,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 9,
  },
  {
    id: 'enemy_attack_the_plague_lord',
    classId: 'warrior' as any,
    name: 'Blight Touch',
    description: 'Pestilent strike.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'mana',
    secondaryScalingStat: 'health',
    baseValue: 8,
    skillMultiplier: 1.1,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 10,
  },
  {
    id: 'enemy_attack_the_anomaly',
    classId: 'warrior' as any,
    name: 'Void Lash',
    description: 'Reality-warping strike.',
    skillType: 'basic',
    costType: 'none',
    manaCost: 0,
    cooldownTurns: 0,
    hpCostPct: 0,
    scalingStat: 'strength',
    secondaryScalingStat: 'mana',
    baseValue: 10,
    skillMultiplier: 1.0,
    targetType: 'single_enemy',
    hitCount: 1,
    unlockRank: 0,
    effectTags: ['damage'],
    ctCost: 10,
  },
];

function validateTickConfigCoverage(): void {
  const allSkills: SkillDefinition[] = [
    ...PRIMARY_CLASS_DEFINITIONS.flatMap(cls =>
      cls.skills.filter((s): s is SkillDefinition => s.skillType !== 'passive'),
    ),
    ...SECONDARY_CLASS_DEFINITIONS.flatMap(cls =>
      cls.skills.filter((s): s is SkillDefinition => s.skillType !== 'passive'),
    ),
    ...ENEMY_SKILLS,
  ];

  const DOT_SUBTYPES = new Set(['poison', 'burn', 'bleed']);
  const HOT_SUBTYPES = new Set(['regen']);
  const VALID_POLICIES = new Set(['refresh', 'stack', 'unique']);

  const missing: string[] = [];
  const invalid: string[] = [];
  const isValidTick = (value: number, durationTurns: number) =>
    Number.isFinite(value)
    && Number.isFinite(durationTurns)
    && value >= 0
    && value <= 1
    && durationTurns >= 1;

  for (const skill of allSkills) {
    if (skill.effectTags.includes('hot') && !skill.tickConfig?.hot) {
      missing.push(`${skill.id} (missing tickConfig.hot)`);
    } else if (skill.tickConfig?.hot) {
      const hot = skill.tickConfig.hot;
      if (!isValidTick(hot.value, hot.durationTurns)) {
        invalid.push(`${skill.id} (invalid tickConfig.hot)`);
      }
      if (!HOT_SUBTYPES.has(hot.subtype)) {
        invalid.push(`${skill.id} (tickConfig.hot.subtype must be one of ${[...HOT_SUBTYPES].join('|')}, got '${hot.subtype}')`);
      }
      if (hot.stackPolicy && !VALID_POLICIES.has(hot.stackPolicy)) {
        invalid.push(`${skill.id} (tickConfig.hot.stackPolicy invalid: '${hot.stackPolicy}')`);
      }
    }
    if (skill.effectTags.includes('dot') && !skill.tickConfig?.dot) {
      missing.push(`${skill.id} (missing tickConfig.dot)`);
    } else if (skill.tickConfig?.dot) {
      const dot = skill.tickConfig.dot;
      if (!isValidTick(dot.value, dot.durationTurns)) {
        invalid.push(`${skill.id} (invalid tickConfig.dot)`);
      }
      if (!DOT_SUBTYPES.has(dot.subtype)) {
        invalid.push(`${skill.id} (tickConfig.dot.subtype must be one of ${[...DOT_SUBTYPES].join('|')}, got '${dot.subtype}')`);
      }
      if (dot.stackPolicy && !VALID_POLICIES.has(dot.stackPolicy)) {
        invalid.push(`${skill.id} (tickConfig.dot.stackPolicy invalid: '${dot.stackPolicy}')`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(`HoT/DoT skills must define tickConfig: ${missing.join(', ')}`);
  }
  if (invalid.length > 0) {
    throw new Error(`HoT/DoT tickConfig contains invalid values: ${invalid.join(', ')}`);
  }
}

validateTickConfigCoverage();

/**
 * Flat skill registry built once at module load. Includes every class skill,
 * enemy skill, and gear ability — keyed by ID. The combat engine resolves all
 * skills through this single map via `getSkillById`; there is no per-source
 * branching, no fall-through chain, no second registry.
 *
 * Gear abilities live in their own file (GearAbilityDefinitions.ts) for
 * organisation, but get merged in here so the engine sees one canonical
 * lookup. Collisions across sources throw at module load — IDs must be
 * globally unique across class skills, enemy skills, and gear abilities.
 */
const ALL_SKILLS_INDEX: Record<string, SkillDefinition | PassiveDefinition> = (() => {
  const index: Record<string, SkillDefinition | PassiveDefinition> = {};
  const sources: Record<string, string> = {};
  const register = (skill: SkillDefinition | PassiveDefinition, source: string) => {
    if (index[skill.id]) {
      throw new Error(
        `Skill ID collision: '${skill.id}' is defined in both '${sources[skill.id]}' and '${source}'`,
      );
    }
    index[skill.id] = skill;
    sources[skill.id] = source;
  };
  for (const cls of PRIMARY_CLASS_DEFINITIONS) {
    for (const s of cls.skills) register(s, `primary:${cls.id}`);
  }
  for (const cls of SECONDARY_CLASS_DEFINITIONS) {
    for (const s of cls.skills) register(s, `secondary:${cls.id}`);
  }
  for (const s of ENEMY_SKILLS) register(s, 'enemy');
  for (const s of Object.values(GEAR_ABILITIES)) register(s, 'gear');
  return index;
})();

/** Lookup a skill by ID across class skills, enemy skills, and gear abilities. */
export function getSkillById(skillId: string): SkillDefinition | PassiveDefinition | undefined {
  return ALL_SKILLS_INDEX[skillId];
}

/** Map an expense category to a boss archetype. Falls back to 'the_anomaly'. */
export function getBossArchetype(category: string): BossArchetypeMapping {
  return (
    BOSS_ARCHETYPE_MAPPINGS.find(m => m.expenseCategory === category) ??
    BOSS_ARCHETYPE_MAPPINGS[BOSS_ARCHETYPE_MAPPINGS.length - 1] // the_anomaly
  );
}

/** Base reward for a quest of a given difficulty. Multiply by rewardScale. */
export function getBaseQuestReward(difficulty: number): { xp: number; gold: number; classRankXP: number } {
  return {
    xp: 10 + difficulty * 5,
    gold: 5 + difficulty * 3,
    classRankXP: 2 + difficulty,
  };
}
