import { UNSPECIFIED, type ClassData } from '../types';

const emberInitiate: ClassData = {
  id: 'drakehorn_forge.ember_initiate',
  name: 'Plasma Runner',
  lineageId: 'drakehorn_forge',
  tier: 1,
  role: 'DPS',
  combatArchetype: 'burst_dps',
  coreLoop: 'Build Heat via basic attacks and Plasma Burst, then vent it for amplified thermal damage.',
  damageIdentity: 'Medium-range plasma projectiles with ramping burst on repeat casts.',
  survivalIdentity: 'Thermal Barrier absorbs a hit and retaliates with plasma feedback on break.',
  ctProfile: 'Medium',
  ctRange: { min: 30, max: 50 },
  primaryResource: 'MP',
  basicAttackSkillId: 'drakehorn.flame_snap',
  skillIds: [
    'drakehorn.fire_bolt',
    'drakehorn.flame_burst',
    'drakehorn.spark_armor',
    'drakehorn.combustion',
  ],
  description: 'A frontline striker wielding plasma-charged blades. Builds Heat with every strike, then vents it in a devastating thermal explosion.',
  gearSynergy: 'Thermal damage boosters; items converting HP to plasma damage.',
  evolutionTargetClassIds: [
    'drakehorn_forge.flame_berserker',
    'thorn_ledger.plague_hunter',
    'tide_shell.blink_assassin',
  ],
  passives: [
    {
      rank: 1,
      name: 'Pyromancy',
      description: '+5% Fire damage.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'fire_damage',
    },
    {
      rank: 3,
      name: 'Flare',
      description: '+3% Intellect.',
      magnitude: 0.03,
      magnitudeUnit: 'percent',
      statTag: 'intellect',
    },
    {
      rank: 5,
      name: 'Blazing Focus',
      description: 'Fire Bolt deals +10% damage after using Combustion.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 7,
      name: 'Ember Shield',
      description: 'While Spark Armor is active, +5% Crit chance.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'crit_chance',
    },
    {
      rank: 9,
      name: 'Heat Surge',
      description: 'After an enemy takes DoT from Flame Burst, gain +5% Strength for 3s.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'strength',
    },
    {
      rank: 10,
      name: 'Lava Heart',
      description: 'If Spark Armor breaks, deal 15% of max HP as AoE fire damage.',
      magnitude: 0.15,
      magnitudeUnit: 'max_hp_percent',
    },
  ],
};

const flameBerserker: ClassData = {
  id: 'drakehorn_forge.flame_berserker',
  name: 'Fusion Caster',
  lineageId: 'drakehorn_forge',
  tier: 2,
  role: 'DPS',
  combatArchetype: 'sustain_dps',
  coreLoop: 'Spend HP on Overclock / Ignite; recover via System Feedback and Reactor Core auto-procs.',
  damageIdentity: 'HP-fueled plasma DPS that scales while systems are critical.',
  survivalIdentity: 'Lifesteal passives and Emergency Vent refund HP after overclocking.',
  ctProfile: 'Medium-Fast',
  ctRange: { min: 25, max: 40 },
  primaryResource: 'HP',
  basicAttackSkillId: 'drakehorn.molten_strike',
  skillIds: [
    'drakehorn.ignite',
    'drakehorn.raging_inferno',
    'drakehorn.berserkers_pact',
    'drakehorn.rage_fuel',
  ],
  description: 'An augmented operative overclocking plasma systems beyond safety limits. Converts HP into devastating thermal output.',
  gearSynergy: 'HP leech and crit boosters; implants granting extra crit on burning targets.',
  evolutionTargetClassIds: [
    'drakehorn_forge.pyre_warlord',
    'thorn_ledger.rot_alchemist',
    'tide_shell.phase_walker',
  ],
  passives: [
    {
      rank: 2,
      name: "Fury's Toll",
      description: '+5% Strength.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'strength',
    },
    {
      rank: 4,
      name: 'Burning Rage',
      description: '+10% Fire damage when HP <50%.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 6,
      name: 'Undying Embers',
      description: 'Recover 5% max HP after Berserker’s Pact.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
    },
    {
      rank: 8,
      name: 'Rage Surge',
      description: 'Rage Fuel duration +2s.',
      magnitude: 2,
      magnitudeUnit: 'seconds',
    },
    {
      rank: 10,
      name: 'Pyreheart',
      description: 'Auto-cast Ignite on any enemy below 20% HP (CD 10s).',
      magnitude: 0.2,
      magnitudeUnit: 'percent',
    },
  ],
};

const pyreWarlord: ClassData = {
  id: 'drakehorn_forge.pyre_warlord',
  name: 'Pyre Warlord',
  lineageId: 'drakehorn_forge',
  tier: 3,
  role: 'Hybrid',
  combatArchetype: 'support',
  coreLoop: 'Stack Warpath buffs, amplify AoE via Dragon’s Breath, refresh cooldowns on multi-hits.',
  damageIdentity: 'AoE fire bursts that scale with active self-buffs.',
  survivalIdentity: 'Ashen Armor defense window plus Battle Cry lifesteal sustain.',
  ctProfile: 'Medium',
  ctRange: { min: 40, max: 60 },
  primaryResource: 'MP',
  basicAttackSkillId: 'drakehorn.warhammer_smash',
  skillIds: [
    'drakehorn.warpath',
    'drakehorn.volcanic_eruption',
    'drakehorn.dragons_breath',
    'drakehorn.battle_cry',
  ],
  description: 'A strategic general commanding fiery assaults.',
  gearSynergy: 'Elemental burst; attack buffs.',
  evolutionTargetClassIds: [
    'drakehorn_forge.inferno_executioner',
    'thorn_ledger.blight_tyrant',
    'tide_shell.dimensional_hunter',
  ],
  passives: [
    {
      rank: 2,
      name: 'Tactical Flame',
      description: 'Warpath strikes do +10% damage.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 4,
      name: 'Ashen Armor',
      description: 'After Warpath, +10% defense for 5s.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
      statTag: 'defense',
    },
    {
      rank: 6,
      name: 'Volcanic Blood',
      description: '+5% Max HP.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'max_hp',
    },
    {
      rank: 8,
      name: 'Ember of War',
      description: 'Battle Cry also grants 5% lifesteal.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'lifesteal',
    },
    {
      rank: 10,
      name: 'Rallying Pyre',
      description: 'Hitting 3+ targets with Dragon’s Breath reduces its cooldown by 5s.',
      magnitude: 5,
      magnitudeUnit: 'seconds',
    },
  ],
};

const infernoExecutioner: ClassData = {
  id: 'drakehorn_forge.inferno_executioner',
  name: 'Solar Executor',
  lineageId: 'drakehorn_forge',
  tier: 4,
  role: 'DPS',
  combatArchetype: 'burst_dps',
  coreLoop: 'Soften with Hellfire DoT, hard-terminate with Executor\u2019s Flame / Final Blaze on low-HP targets.',
  damageIdentity: 'Execute-threshold burst; Final Blaze resets cooldowns to chain eliminations.',
  survivalIdentity: 'Kill-on-termination shield (Ash Protocol) and raw offensive tempo.',
  ctProfile: 'Slow',
  ctRange: { min: 60, max: 80 },
  primaryResource: 'None',
  basicAttackSkillId: 'drakehorn.blazing_axe',
  skillIds: [
    'drakehorn.hellfire',
    'drakehorn.demolisher',
    'drakehorn.executioners_flame',
    'drakehorn.final_blaze',
  ],
  description: 'An elimination specialist who terminates weakened targets with concentrated solar plasma.',
  gearSynergy: 'High damage or life-leech; extra-HP implants amplify Final Blaze.',
  evolutionTargetClassIds: [
    'drakehorn_forge.apocalypse_bringer',
    'thorn_ledger.death_bloom_entity',
    'tide_shell.singularity_fracture',
  ],
  passives: [
    {
      rank: 2,
      name: "Executioner's Resolve",
      description: '+5% Strength.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'strength',
    },
    {
      rank: 4,
      name: 'Overheat',
      description: 'Hellfire DoT +5% damage.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
    },
    {
      rank: 6,
      name: 'Blood of Ashes',
      description: 'Gain shield equal to 10% max HP when Executioner’s Flame kills.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 8,
      name: 'Cindered Spirit',
      description: '+5% Crit chance.',
      magnitude: 0.05,
      magnitudeUnit: 'percent',
      statTag: 'crit_chance',
    },
    {
      rank: 10,
      name: 'Infernal Legacy',
      description: 'After Final Blaze, all skill cooldowns reduced by 50%.',
      magnitude: 0.5,
      magnitudeUnit: 'percent',
    },
  ],
};

const apocalypseBringer: ClassData = {
  id: 'drakehorn_forge.apocalypse_bringer',
  name: 'Nova Obliterator',
  lineageId: 'drakehorn_forge',
  tier: 5,
  role: 'DPS',
  combatArchetype: 'trickster',
  coreLoop: 'Ignite the field with Plasma Storm, nuke with Cataclysm, chain ultimates via System Reboot resets.',
  damageIdentity: 'Battlefield-wide plasma pressure scaling with active buffs and multi-kills.',
  survivalIdentity: 'Reactor Core post-revive window plus Emergency Power passive ceiling.',
  ctProfile: 'Slow',
  ctRange: { min: 80, max: 100 },
  primaryResource: 'None',
  basicAttackSkillId: 'drakehorn.world_on_fire',
  skillIds: [
    'drakehorn.cataclysm',
    'drakehorn.black_hole',
    'drakehorn.wrath_of_the_phoenix',
    'drakehorn.end_of_days',
  ],
  description: 'The apex plasma operative. Commands battlefield-wide thermal annihilation with orbital-grade weaponry.',
  gearSynergy: 'Highest-tier damage gear; ultimate-boosting items.',
  evolutionTargetClassIds: [],
  passives: [
    {
      rank: 1,
      name: "Bringer's Fury",
      description: '+10% Fire damage.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 3,
      name: 'Fallen Warrior',
      description: '+10% damage if any ally fell that fight.',
      magnitude: 0.1,
      magnitudeUnit: 'percent',
    },
    {
      rank: 5,
      name: 'Phoenix Heart',
      description: 'After Wrath triggers, gain +30% damage for 10s.',
      magnitude: 0.3,
      magnitudeUnit: 'percent',
    },
    {
      rank: 7,
      name: 'Infernal Wrath',
      description: 'Cataclysm damage +30% vs grouped enemies.',
      magnitude: 0.3,
      magnitudeUnit: 'percent',
    },
    {
      rank: 9,
      name: 'Undying Flame',
      description: '+15% All damage (passive).',
      magnitude: 0.15,
      magnitudeUnit: 'percent',
    },
    {
      rank: 10,
      name: 'Armageddon',
      description: 'End of Days resets all other cooldowns if it kills 3+ enemies.',
      magnitude: 0.3,
      magnitudeUnit: 'percent',
    },
  ],
};

export const DRAKEHORN_CLASSES: readonly ClassData[] = [
  emberInitiate,
  flameBerserker,
  pyreWarlord,
  infernoExecutioner,
  apocalypseBringer,
];
