import { UNSPECIFIED, type ClassData, type ClassTier, type LineageId } from '../types';

const BULL_CATHEDRAL_CLASSES: readonly ClassData[] = [
  {
    id: 'bull_cathedral.shield_initiate',
    name: 'Shield Initiate',
    lineageId: 'bull_cathedral',
    tier: 1,
    role: 'Tank',
    combatArchetype: 'tank',
    ctProfile: 'Medium',
    ctRange: { min: 35, max: 55 },
    primaryResource: 'MP',
    basicAttackSkillId: 'bull.shield_tap',
    skillIds: ['bull.guard_up', 'bull.sanctuary_swing', 'bull.oath_line', 'bull.reprisal_mark'],
    passives: [
      {
        rank: 1,
        name: 'Stone Discipline',
        description: 'Gain baseline Guard at battle start.',
        magnitude: UNSPECIFIED,
        statTag: 'guard_stacks',
      },
      {
        rank: 3,
        name: 'Oathful Brace',
        description: 'Guard Up grants additional mitigation.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
        statTag: 'damage_reduction',
      },
      {
        rank: 5,
        name: 'Measured Reprisal',
        description: 'Marked enemies take additional counter damage.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
    evolutionTargetClassIds: ['bull_cathedral.bastion_guard'],
    description:
      'Entry Bull Cathedral class focused on building Guard and stabilizing allied frontlines.',
    gearSynergy: 'Shield-strength and mitigation gear; counter-support relics.',
    coreLoop: 'Build Guard via stance and incoming hits, then convert Guard into retaliation bursts.',
    damageIdentity: 'Guard-scaled single-target punishment with reprisal marks.',
    survivalIdentity: 'Early mitigation posture and ally damage redirection.',
  },
  {
    id: 'bull_cathedral.bastion_guard',
    name: 'Bastion Guard',
    lineageId: 'bull_cathedral',
    tier: 2,
    role: 'Tank',
    combatArchetype: 'tank',
    ctProfile: 'Medium-Slow',
    ctRange: { min: 45, max: 65 },
    primaryResource: 'MP',
    basicAttackSkillId: 'bull.bastion_hammer',
    skillIds: ['bull.guard_slam', 'bull.bulwark_pulse', 'bull.sanctum_vow', 'bull.wardens_call'],
    passives: [
      {
        rank: 2,
        name: 'Weight of Stone',
        description: 'Guard Slam consumes fewer Guard stacks for full value.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 4,
        name: 'Shared Cover',
        description: 'Bulwark Pulse shields allies for a larger amount.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 6,
        name: "Called to Stand",
        description: "Warden's Call generates bonus Guard when focused.",
        magnitude: UNSPECIFIED,
        statTag: 'guard_stacks',
      },
    ],
    evolutionTargetClassIds: ['bull_cathedral.fortress_knight'],
    description: 'Reinforced sanctuary defender that converts Guard into stronger party shielding.',
    gearSynergy: 'Barrier scaling and taunt-control modifiers.',
    coreLoop: 'Hold focus, pulse shields to allies, and spend Guard on hammer slams.',
    damageIdentity: 'Defensive burst scaling off Guard consumption.',
    survivalIdentity: 'Sustained mitigation with reactive Guard generation under pressure.',
  },
  {
    id: 'bull_cathedral.fortress_knight',
    name: 'Fortress Knight',
    lineageId: 'bull_cathedral',
    tier: 3,
    role: 'Support',
    combatArchetype: 'support',
    ctProfile: 'Medium',
    ctRange: { min: 40, max: 60 },
    primaryResource: 'MP',
    basicAttackSkillId: 'bull.fortress_strike',
    skillIds: [
      'bull.shared_bulwark',
      'bull.pillar_crash',
      'bull.anchored_stance',
      'bull.consecrated_wall',
    ],
    passives: [
      {
        rank: 2,
        name: 'Formation Tutor',
        description: 'Shared Bulwark scales harder with active Guard.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 5,
        name: 'Anchor Tempo',
        description: 'Anchored Stance grants stronger CT discounts to defensive actions.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 8,
        name: 'Sanctified Citadel',
        description: 'Consecrated Wall duration is extended.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'seconds',
      },
    ],
    evolutionTargetClassIds: ['bull_cathedral.iron_warder'],
    description: 'Midline bastion that shares Guard value as team protection and tempo control.',
    gearSynergy: 'Support barriers, cooldown economy, and defensive aura extensions.',
    coreLoop: 'Convert your Guard state into ally shields and safer cadence windows.',
    damageIdentity: 'Area control through Guard-amplified crash patterns.',
    survivalIdentity: 'Group-focused sanctuaries and CT-efficient defensive rotations.',
  },
  {
    id: 'bull_cathedral.iron_warder',
    name: 'Iron Warder',
    lineageId: 'bull_cathedral',
    tier: 4,
    role: 'Tank',
    combatArchetype: 'tank',
    ctProfile: 'Medium-Slow',
    ctRange: { min: 55, max: 75 },
    primaryResource: 'MP',
    basicAttackSkillId: 'bull.warder_pike',
    skillIds: ['bull.unyielding_taunt', 'bull.ct_shackle', 'bull.covenant_ram', 'bull.guard_hegemony'],
    passives: [
      {
        rank: 3,
        name: 'Iron Rebuke',
        description: 'Enemies affected by Unyielding Taunt lose additional CT when striking you.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 6,
        name: 'Shackle Mastery',
        description: 'CT Shackle debuff duration is extended.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'seconds',
      },
      {
        rank: 9,
        name: 'Guard Dominion',
        description: 'Guard Hegemony gains additional mitigation conversion.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
    evolutionTargetClassIds: ['bull_cathedral.immutable_wall'],
    description: 'Control-focused warder that enforces enemy tempo loss under taunt pressure.',
    gearSynergy: 'CT control amplifiers and high-mitigation conversion sets.',
    coreLoop: 'Pin enemy tempo with taunt + CT shackle, then cash out Guard into hegemony windows.',
    damageIdentity: 'Cone burst and reprisal scaling under control states.',
    survivalIdentity: 'High uptime control-tank pattern with strong mitigation conversion.',
  },
  {
    id: 'bull_cathedral.immutable_wall',
    name: 'Immutable Wall',
    lineageId: 'bull_cathedral',
    tier: 5,
    role: 'Control',
    combatArchetype: 'trickster',
    ctProfile: 'Slow',
    ctRange: { min: 70, max: 95 },
    primaryResource: 'MP',
    basicAttackSkillId: 'bull.wallbreaker_maul',
    skillIds: ['bull.law_of_shelter', 'bull.citadel_domain', 'bull.bastion_edict', 'bull.immovable_decree'],
    passives: [
      {
        rank: 4,
        name: 'Civic Law',
        description: 'Law of Shelter grants stronger shield-floor protection.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 7,
        name: 'Domain Authority',
        description: 'Citadel Domain amplifies both ally defense and enemy damage penalty.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
      {
        rank: 10,
        name: 'Immovable Mandate',
        description: 'Immovable Decree grants stronger CT-shift resistance to allies.',
        magnitude: UNSPECIFIED,
        magnitudeUnit: 'percent',
      },
    ],
    evolutionTargetClassIds: [],
    description: 'Apex Bull Cathedral authority form that enforces sanctuary law across the battlefield.',
    gearSynergy: 'Capstone barrier scaling, team mitigation auras, and CT-resistance gear.',
    coreLoop: 'Establish sanctuary law windows and suppress enemy throughput while allies stabilize.',
    damageIdentity: 'Guard-amplified decree strikes with battlefield debuff support.',
    survivalIdentity: 'Party-wide shield floor and CT resistance against disruptive effects.',
  },
];

type StubTuple = readonly [tier: ClassTier, idSuffix: string, displayName: string];

const LINEAGE_CLASS_TABLE: readonly (readonly [LineageId, readonly StubTuple[]])[] = [
  [
    'twin_mirror',
    [
      [5, 'arcane_initiate', 'Arcane Initiate'],
      [4, 'spellbinder', 'Spellbinder'],
      [3, 'chaos_mage', 'Chaos Mage'],
      [2, 'reality_weaver', 'Reality Weaver'],
      [1, 'probability_architect', 'Probability Architect'],
    ],
  ],
  [
    'tide_shell',
    [
      [5, 'rift_initiate', 'Rift Initiate'],
      [4, 'blink_assassin', 'Blink Assassin'],
      [3, 'phase_walker', 'Phase Walker'],
      [2, 'dimensional_hunter', 'Dimensional Hunter'],
      [1, 'singularity_fracture', 'Singularity Fracture'],
    ],
  ],
  [
    'sunfang_court',
    [
      [5, 'aspirant_radiant', 'Aspirant Radiant'],
      [4, 'dawnblade_initiate', 'Dawnblade Initiate'],
      [3, 'solarian_vanguard', 'Solarian Vanguard'],
      [2, 'lumen_judge', 'Lumen Judge'],
      [1, 'helios_arbiter', 'Helios Arbiter'],
    ],
  ],
  [
    'thorn_ledger',
    [
      [5, 'venom_initiate', 'Venom Initiate'],
      [4, 'plague_hunter', 'Plague Hunter'],
      [3, 'rot_alchemist', 'Rot Alchemist'],
      [2, 'blight_tyrant', 'Blight Tyrant'],
      [1, 'death_bloom_entity', 'Death Bloom Entity'],
    ],
  ],
  [
    'balance_reins',
    [
      [5, 'grace_initiate', 'Grace Initiate'],
      [4, 'light_herald', 'Light Herald'],
      [3, 'sanctum_protector', 'Sanctum Protector'],
      [2, 'divine_ascendant', 'Divine Ascendant'],
      [1, 'judgment_vessel', 'Judgment Vessel'],
    ],
  ],
  [
    'black_nest',
    [
      [5, 'shade_initiate', 'Shade Initiate'],
      [4, 'nightblade', 'Nightblade'],
      [3, 'eclipse_stalker', 'Eclipse Stalker'],
      [2, 'void_reaver', 'Void Reaver'],
      [1, 'abyss_sovereign', 'Abyss Sovereign'],
    ],
  ],
  [
    'arrow_creed',
    [
      [5, 'gale_initiate', 'Gale Initiate'],
      [4, 'wind_striker', 'Wind Striker'],
      [3, 'storm_runner', 'Storm Runner'],
      [2, 'cyclone_duelist', 'Cyclone Duelist'],
      [1, 'skyfracture_herald', 'Skyfracture Herald'],
    ],
  ],
  [
    'iron_covenant',
    [
      [5, 'stone_initiate', 'Stone Initiate'],
      [4, 'earthbreaker', 'Earthbreaker'],
      [3, 'mountain_sentinel', 'Mountain Sentinel'],
      [2, 'world_anchor', 'World Anchor'],
      [1, 'titan_core', 'Titan Core'],
    ],
  ],
  [
    'star_circuit',
    [
      [5, 'time_initiate', 'Time Initiate'],
      [4, 'temporal_slicer', 'Temporal Slicer'],
      [3, 'ct_strategist', 'CT Strategist'],
      [2, 'chrono_breaker', 'Chrono Breaker'],
      [1, 'timeline_disruptor', 'Timeline Disruptor'],
    ],
  ],
  [
    'dream_ocean',
    [
      [5, 'fang_initiate', 'Fang Initiate'],
      [4, 'predator_warrior', 'Predator Warrior'],
      [3, 'apex_hunter', 'Apex Hunter'],
      [2, 'alpha_devourer', 'Alpha Devourer'],
      [1, 'primal_overlord', 'Primal Overlord'],
    ],
  ],
];

function stubClass(
  lineageId: LineageId,
  tier: ClassTier,
  idSuffix: string,
  name: string,
): ClassData {
  return {
    id: `${lineageId}.${idSuffix}`,
    name,
    lineageId,
    tier,
    role: 'DPS',
    combatArchetype: 'burst_dps',
    ctProfile: 'Medium',
    ctRange: UNSPECIFIED,
    primaryResource: 'None',
    basicAttackSkillId: UNSPECIFIED,
    skillIds: [],
    passives: [],
    evolutionTargetClassIds: [],
    description: `Stub for ${name} (${lineageId} T${tier}). Authored in P1.5.`,
    gearSynergy: '',
    isStub: true,
  };
}

const NON_BULL_STUB_CLASSES: readonly ClassData[] = LINEAGE_CLASS_TABLE.flatMap(
  ([lineageId, entries]) =>
    entries.map(([tier, idSuffix, name]) => stubClass(lineageId, tier, idSuffix, name)),
);

export const STUB_CLASSES: readonly ClassData[] = [
  ...BULL_CATHEDRAL_CLASSES,
  ...NON_BULL_STUB_CLASSES,
];
